### ISSUE TITLE
Why must use Android Studio Arctic Fox Beta?

### ISSUE THREAD

**Issue by jinkg** [livekit/client-sdk-android#1]
I'm try to use the repo on Android Studio 4.2.2, but report Unresolved reference: livekit...

e: PublisherTransportObserver.kt: (4, 8): Unresolved reference: livekit
e: PublisherTransportObserver.kt: (16, 57): Unresolved reference: LivekitRtc

**Comment by jinkg** [comment]
Android Studio Arctic Fox Beta report error above too

**Comment by davidzhao** [comment]
You need to checkout the shared protocol repo as well: https://github.com/livekit/client-sdk-android#dev-environment
