### ISSUE TITLE
Unmuting after reconnection does not work

### ISSUE THREAD

**Issue by symphonybiz** [livekit/client-sdk-android#109]
If LiveKit reconnection happens while I'm muted, then after successful reconnection I have to unmute/mute/unmute myself to get my audio stream working (the first unmute does nothing).

This is reproducible in the sample app.

Repro steps:
- Connect 2 clients on 2 different devices (device-1 and device-2) to the same room
- Test that audio sent from device-1 is heard on device-2
- Mute local participant on device-1
- Put device-1 in airplane mode
- Turn off airplane mode on device-1
- Unmute local participant on device-1: audio is not heard on device-2. NOK
then:
- Mute and unmute local participant on device-1: audio is heard on device-2

**Comment by davidliu** [comment]
@symphonybiz Thanks for the report, I'll look into fixing this soon.

----

this issue is because we can't publish a muted track.

In JS, we only republish the track after reconnect if it's not muted

**Comment by symphonybiz** [comment]
@davidliu our testers have reported that this is fixed after the changes you made, so we it can be closed from my POV
