### ISSUE TITLE
Can i use simulcast with VP8 Codec

### ISSUE THREAD

**Issue by ducanh3005** [livekit/client-sdk-android#122]
I tried to use SimulcastVideoEncoderFactoryWrapper class and i saw that codec i used is H264 so can you help me to change codec to VP8.

**Comment by ducanh3005** [comment]
![Screen Shot 2022-07-26 at 11 09 54](https://user-images.githubusercontent.com/61770725/180921105-6e1c2020-8f5d-4149-9c2e-8bc92b6db0b6.png)

**Comment by davidliu** [comment]
Check this out for reference:

 https://github.com/livekit/client-sdk-android/blob/main/video-encode-decode-test/src/main/java/io/livekit/android/videoencodedecode/WhitelistSimulcastVideoEncoderFactory.kt

It allows you to specify which video codecs you want to use. Pass in "VP8" to limit it only to VP8.
