### ISSUE TITLE
Video Not Rendering Created new app using Readme

### ISSUE THREAD

**Issue by Yashgugaliya** [livekit/client-sdk-android#123]
2022-07-26 13:03:28.237 17201-17370/com.example.livekit W/AudioCapabilities: Unsupported mime audio/x-ima
2022-07-26 13:03:28.242 17201-17370/com.example.livekit W/AudioCapabilities: Unsupported mime audio/mpeg-L1
2022-07-26 13:03:28.243 17201-17370/com.example.livekit W/AudioCapabilities: Unsupported mime audio/mpeg-L2
2022-07-26 13:03:28.244 17201-17370/com.example.livekit W/AudioCapabilities: Unsupported mime audio/x-ms-wma
2022-07-26 13:03:28.295 17201-17370/com.example.livekit W/VideoCapabilities: Unsupported mime video/wvc1
2022-07-26 13:03:28.353 17201-17370/com.example.livekit W/VideoCapabilities: Unsupported mime video/mp43
2022-07-26 13:03:28.355 17201-17370/com.example.livekit W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
2022-07-26 13:03:28.355 17201-17370/com.example.livekit W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
2022-07-26 13:03:28.355 17201-17370/com.example.livekit W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
2022-07-26 13:03:28.357 17201-17370/com.example.livekit W/VideoCapabilities: Unsupported mime video/wvc1
2022-07-26 13:03:28.361 17201-17370/com.example.livekit W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
2022-07-26 13:03:28.362 17201-17370/com.example.livekit W/VideoCapabilities: Unsupported mime video/x-ms-wmv8

**Comment by davidliu** [comment]
What device and OS are you using?

**Comment by Yashgugaliya** [comment]
I am tried with Android and devices samsung, Redmi , Google (Api 30,31).

Android Studio version bumblebee
OS - MAC OS Montery 

i have used this code snippet in  new Android Studio project 

dependencies {
  implementation "io.livekit:livekit-android:1.1.1"
  // Snapshots of the latest development version are available at:
  // implementation "io.livekit:livekit-android:1.1.2-SNAPSHOT"
}

MainActivity
Class MainActivity : AppCompatActivity(), RoomListener {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        ...
        val url = "wss://your_host";
        val token = "your_token"

        lifecycleScope.launch {
            // Create Room object.
            val room = LiveKit.create(
                applicationContext,
                RoomOptions(),
            )
        
            // Setup event handling.
            launch {
                room.events.collect { event ->
                    when(event){
                        is RoomEvent.TrackSubscribed -> onTrackSubscribed(event)
                    }
                }
            }
            
            // Connect to server.
            room.connect(
                url,
                token,
                ConnectOptions()
            )
            
            // Turn on audio/video recording.
            val localParticipant = room.localParticipant
            localParticipant.setMicrophoneEnabled(true)
            localParticipant.setCameraEnabled(true)
        }
    }

    private fun onTrackSubscribed(event: RoomEvent.TrackSubscribed) {
        if (event.track is VideoTrack) {
            attachVideo(track)
        }
    }

    private fun attachVideo(videoTrack: VideoTrack) {
        // viewBinding.renderer is a `io.livekit.android.renderer.SurfaceViewRenderer` in your
        // layout
        videoTrack.addRenderer(viewBinding.renderer)
    }
}

**Comment by Yashgugaliya** [comment]
It would be great if i get an sample app or good doc with dependencies included sample project  implementation so it could be easy for other devs also cause https://github.com/livekit/client-sdk-android/tree/main/sample-app  this is little Confusing

**Comment by davidliu** [comment]
For the sample app, what parts do you find confusing? I'll look into updating the documentation there; it'd help if you could note what's missing.

**Comment by Yashgugaliya** [comment]
OK in sample app doc 
attachVideo(track)
track has not declared so i can't find what is and  protocal  should be included in other apps where i am using livekit and after do lot of R&D i cant render simple video also so atleat an sample app can me made using liveKit dependencies with some simple like showing speaker and particpant view something like this https://github.com/davidliu/LiveKitCompile  which you devloped only to compile livekit dependency  with above features so i think it could help others. 
you can refer this link https://www.100ms.live/docs/android/v2/features/Integration some thing quite simple like this 
and sample app like this https://github.com/100mslive/100ms-android would help me as well as other devlopers and OSP community.

**Comment by davidliu** [comment]
Thanks for the suggestions, I'll look into adding them.

**Comment by davidliu** [comment]
Hey @Yashgugaliya, I've updated the README and added a much simpler basic version of the sample app [here](https://github.com/livekit/client-sdk-android/tree/main/sample-app-basic). Let me know if you have any further suggestions.

**Comment by Yashgugaliya** [comment]
HI @davidliu  sample app [here](https://github.com/livekit/client-sdk-android/tree/main/sample-app-basic)  Crash when trying to run. Readme look better still confued in protocol module .
i will explain you my case i want to integrate video meeting in my app 
so i have created new Android Project and added live kit Dependencies in my gradle and add sample-app-basic MainActivity code and xml and from it and trying to run i got token for now from playround so using it for testing when trying to run only progress bar is showing no video rendreing .
So it would be great if you create an sample app in new project not inside this https://github.com/livekit/client-sdk-android repo . create new Repo and add liveKit This way implementation 'io.livekit:livekit-android:1.1.1' 
not like this implementation project(":livekit-android-sdk") and little bit about protocol module how to add it in my app .
would be great

**Comment by davidliu** [comment]
The protocol module is not needed for building apps. It's only used for building the SDK, and should be ignored unless developing the SDK.

Adding a sample app to a separate repo is probably a no-go for the moment, but I'll add a note in the build.gradle what to change if building independently.

**Comment by Yashgugaliya** [comment]
I Dit it but the Sample App  basic is not rendering the  video only can you run and check it

**Comment by davidliu** [comment]
Do you have another participant connected to it?

**Comment by Yashgugaliya** [comment]
no only one participate

**Comment by Yashgugaliya** [comment]
just trying to run Sample App Basic Only Progress. bar is Runing 
launch {
                room.events.collect { event ->
                    when (event) {
                        is RoomEvent.TrackSubscribed -> onTrackSubscribed(event)
                        else -> {}
                    }
                }
            }
RoomEvent.TrackSubscribed  Event Is not getting trigger 
Else{} its jumping to else part 
did it was runing for you

**Comment by davidliu** [comment]
The sample app will only display the other participant's video, not your
own.

**Comment by Yashgugaliya** [comment]
So how can I test it to render video

**Comment by davidliu** [comment]
Have another participant join the room.
