### ISSUE TITLE
sample-app: the speaking participant has no UI feedback

### ISSUE THREAD

**Issue by tidoemanuele** [livekit/client-sdk-android#125]
**Describe the bug**
The sample-app-compose demo already support UI feedback for the speaking participant but this funcionality is still missed in the sample-app 

**To Reproduce**
1. Connect a room with a valid token 
2. give the mic permission
3. Start talking 
4. Check that there is no visual feedback to the speaking participant

**Expected behavior**
When a participant is speaking should have a visual feedback that identify him as a participant that is speaking 

**Device Info:**
 - Device: Xiaomi Redmi Note 9 Pro
 - OS: Android 11
 - LiveKit SDK version: 1.1.1

**Comment by davidliu** [comment]
Fixed by #126.
