### ISSUE TITLE
Handle POST_NOTIFICATIONS permission for Android 13

### ISSUE THREAD

**Issue by davidliu** [livekit/client-sdk-android#136]
Android 13 has a new POST_NOTIFICATIONS permission:

https://developer.android.com/develop/ui/views/notifications/notification-permission#wait-to-show-prompt

We currently use a foreground service for screensharing, which requires a notification. We should handle requesting this, or document how library consumers should handle this.

**Comment by davidzhao** [comment]
I think if the creator of the service should handle requesting for this permission. So if that's us, then it'd be ideal if SDK would handle it.

**Comment by davidliu** [comment]
Turns out it's an optional permission for our purposes. Added documentation clarifying our behavior in #138.
