### ISSUE TITLE
Release version without compose

### ISSUE THREAD

**Issue by SudoDios** [livekit/client-sdk-android#150]
Hi.
I don't use compose while livekit-android downloads it

**Comment by davidzhao** [comment]
if your app doesn't use compose, it will not be included in the resulting binary.

**Comment by SudoDios** [comment]
Does that mean my software can't use this sdk?

**Comment by davidliu** [comment]
No, it'll simply be stripped out during the optimization process when making a release build.

**Comment by SudoDios** [comment]
Very goood 👍.
thanks 🌹

**Comment by davidliu** [comment]
As a side note, for those avoiding using `minifyEnabled` or simply wish assurance, you can manually exclude the compose dependency in your gradle file like so:

```
implementation("io.livekit:livekit-android:<version>") {
    exclude group: 'androidx.compose.ui', module: 'ui'
}
```
