### ISSUE TITLE
Video not place correct in full window 

### ISSUE THREAD

**Issue by kamaltyagi02** [livekit/client-sdk-android#152]
**To Reproduce**
I integrated version 0.9.1 and even version 1.1.1 of Android SDK

Connecting two android phones A to B, audio and video flows only from one side to another.

However, I see video from the remote side coming into the small window when I scroll sideways in the small window.

It seems like the audio triggers when it starts from the side where the video is supposed to come. So then the video shows in the large main window on the recipient side.

The audio also doesn’t start about 20% of the time.

**Expected behavior**

**Screenshots**

**Device Info:**
 - Device: [e.g. Google Pixel 4]
 - OS: [e.g. Android 12]
 - LiveKit SDK version: 0.9.1 , 1.1.1

**Additional context**

**Comment by davidliu** [comment]
It's a little unclear what you mean here, can you provide screenshots or a reproducible example?

**Comment by davidliu** [comment]
Closing as stale.
