### ISSUE TITLE
Taking around 3 second to Listen voice of opponent users

### ISSUE THREAD

**Issue by deepkiran** [livekit/client-sdk-android#160]
we are trying to use as audio / video call, but when opposite user connect to room, after connection it takes around 3 seconds to wait for voice to listen.

we are just using audio to to connect voice, Video is not enabled for this case./we want to speed up audio call.

1) connect user 1 in room
2) connect user 2 in room, after user connected start counting 1,2,3 ... it will not listen voice immediatly conencted in same room .

Expected behavior
-after user joined in room it should start listening to voice immediatly.

**Device Info:**
 - Device: Google pixel 3,Motorola g60 .
 - OS: [Android 11,Android 12]
 - LiveKit SDK version: [e.g. 1.1.0]

-We have deployed server in our own cloud .

Thanks

**Comment by davidliu** [comment]
Do other platforms behave similarly or faster when connecting to your server?

**Comment by deepkiran** [comment]
android and ios sdk both connects slower.
if any configuration need to be done , pls suggest any changes if nay need to so on server.

**Comment by davidzhao** [comment]
You should see the ping times you are getting between your client and server. WebRTC connections perform several round trips during connection establishment and publishing. Can you try with the [example app](https://example.livekit.io/)? How fast does it publish?

**Comment by kaushaldeepkiran** [comment]
![image](https://user-images.githubusercontent.com/127093040/228255418-eb217d0d-1dfb-4aa5-868a-e624b22aa719.png)


attached screen shot for all Event log.

**Comment by davidzhao** [comment]
Closing as requested information is not provided.
