### ISSUE TITLE
Android 13 bug with Bluetooth Audio device

### ISSUE THREAD

**Issue by rcaceiro** [livekit/client-sdk-android#178]
**Describe the bug**
On android 13 there is an issue that changes the audio from Bluetooth to earpiece instead speakerphone

**To Reproduce**
1. Change the preferredList to `listOf(AudioDevice.BluetoothHeadset::class.java, AudioDevice.WiredHeadset::class.java, AudioDevice.Speakerphone::class.java, AudioDevice.Earpiece::class.java)`

2. Open the sample app, login into the LiveKit server
3. Connect an Bluetooth audio device
5. Disconnect the Bluetooth audio device
6. Check that the sound came out form the earpiece instead of speakerphone

**Expected behavior**
The sound should output thought the speakerphone  

**Device Info:**
 - Device: Samsung A51 5G
 - OS: Android 13
 - LiveKit SDK version: 1.1.6

**Additional context**
I already fixed the issue alongside add some more logs to help debug future problem.
Repo: https://github.com/rcaceiro/audioswitch
Commit: https://github.com/davidliu/audioswitch/commit/582a69b9549b31a1a8d7e0f583f82c523102ea4d

**Comment by davidliu** [comment]
Thanks for the fix!
