### ISSUE TITLE
DataReceived is not getting called

### ISSUE THREAD

**Issue by codelab-sahil** [livekit/client-sdk-android#184]
**Describe the bug**
When data published via Android or iOS participant, data received inside **DataReceived**. But when data triggered from server nothing is received in Android while the same data received in iOS event.

**Device Info:**
 - OS: Android
 - LiveKit SDK version: 1.1.6

**Comment by davidliu** [comment]
What are you using to publish data from the server?

**Comment by codelab-sahil** [comment]
From Android or iOS if participant or host publish data I receive all events in DataReceived. But when it is triggered from server enable to receive any data or even logs. Published data from server is in string format.

**Comment by davidliu** [comment]
What exactly are you using to publish the data from the server?

**Comment by codelab-sahil** [comment]
Below code is triggered from server

> $data = [
	'message' => $message,
	'timestamp' => time(),
	'type' => $type,
	'user' => [
		"last_name" => "test2",
		"profile_image" => "",
		"user_id" => "1",
		"user_type" => "User",
		"first_name" => "test",
		"user_email" => "mailto:abc@yopmail.com"
	]
];

**Comment by codelab-sahil** [comment]
For Receiving data in Android:

> launch {
					room.events.collect { event ->
						when (event) {
							is RoomEvent.FailedToConnect -> {
								log { "Room event error: ${event.error}" }
							}
							is RoomEvent.DataReceived -> {
								val identity = event.participant.identity ?: ""
								val message = event.data.toString(Charsets.UTF_8)
								log { "Room event identity: $identity" }
								log { "Room event message: $message" }
							}
							else -> {
								log { "Room event: $event" }
							}
						}
					}
				}

For Sending data from Android:

> room.localParticipant.publishData(
	jsonObject.toString().toByteArray(Charsets.UTF_8)
)

**Comment by codelab-sahil** [comment]
@davidliu 
Let me know if you want any other information

**Comment by davidliu** [comment]
I'm going to repeat again: What is the code you're using to publish data *from the server*?

Not sure why you're showing me the android implementation, when you said you had no issues publishing from Android.

**Comment by codelab-sahil** [comment]
public function sendData(string $roomName, string $data, int $kind, array $destinationSids = []): SendDataResponse {
    $videoGrant = new VideoGrant();
    $videoGrant->setRoomName($roomName);
    $videoGrant->setRoomAdmin();
    return $this->rpc->SendData(
      $this->authHeader($videoGrant),
      new SendDataRequest([
        'room' => $roomName,
        'data' => $data,
        'kind' => $kind,
        'destination_sids' => $destinationSids,
      ])
    );

**Comment by davidliu** [comment]
Which server sdk is this?

**Comment by codelab-sahil** [comment]
Below server sdk:

https://github.com/agence104/livekit-server-sdk-php

**Comment by codelab-sahil** [comment]
@davidliu Thanks for you support
