### ISSUE TITLE
Room object still hold sid after disconnect

### ISSUE THREAD

**Issue by alxgord** [livekit/client-sdk-android#194]
**Describe the bug**
Failed to connect to another room after session end in current, when using same Room object (sid is the same when attempting to connect after session ended)

**To Reproduce**
1. Connect to room
2. Disconnect from room
3. Use same Room instance to connect another room with new token
4. Disconnection will occur instantly

**Expected behavior**
Successfully connection to new room

**Device Info:**
 - Pixel 6 Pro
 - Android 13
 - LiveKit SDK version: 1.1.5
 
![Screenshot 2023-03-06 at 17 52 02](https://user-images.githubusercontent.com/17838017/223161451-ee08d74c-461f-4dd3-a876-ffdc86ae8145.png)

Please inform me if additional details needed.

**Comment by davidliu** [comment]
For step 4, does this mean that when you try to connect to the server the second time, it disconnects unexpectedly?
