### ISSUE TITLE
Livekit SDK not up to date - participant not disconnected after CallActivity `onExitClick`

### ISSUE THREAD

**Issue by reemaadeniyi** [livekit/client-sdk-android#221]
**Describe the bug**
Livekit SDK not up to date

**To Reproduce**
Bug in a call with 2 participants. When participant 2 closes CallActivity by `onExitClick` participant 1 can still see participant 2 on the call.

**Device Info:**
 - Device: Emulator
 - OS: Android 13
 - LiveKit SDK version: 1.1.10

**Additional context**

According to this file https://github.com/livekit/client-sdk-android/blob/main/sample-app-compose/src/main/java/io/livekit/android/composesample/VideoItem.kt#L62 which is implemented by  https://github.com/livekit/client-sdk-android/blob/main/livekit-android-sdk/src/main/java/io/livekit/android/compose/VideoRenderer.kt#L22

`VideoRenderer ` has `mirror` argument but when you use `VideoRenderer` from the library `implementation "io.livekit:livekit-android:1.1.10"` `mirror` is not available.

**Comment by davidliu** [comment]
Please file separate bugs if you have multiple issues.

The VideoRenderer `mirror` argument is recently added and will be released soon. Please understand that we won't make a new release after every commit. If you want to try out the latest commits, you can always try the SNAPSHOT version (currently `1.1.11-SNAPSHOT`).

**Comment by davidliu** [comment]
Closing this issue. Open a new issue for the `onExitClick` if you still see that issue. I'm unable to repro this on `sample-app` nor `sample-app-compose`.
