### ISSUE TITLE
'import livekit.*' not find

### ISSUE THREAD

**Issue by Oliver-WJ** [livekit/client-sdk-android#222]
I didn't find anything about 'livekit.*' package

sdk:compileDebugKotlin FAILED
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/events/RoomEvent.kt: (9, 8): Unresolved reference: livekit
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/events/RoomEvent.kt: (197, 5): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/events/RoomEvent.kt: (198, 12): 'when' expression must be exhaustive, add necess
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/PublisherTransportObserver.kt: (4, 8): Unresolved reference: livekit
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/PublisherTransportObserver.kt: (20, 50): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (24, 8): Unresolved reference: livekit
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (25, 8): Unresolved reference: livekit
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (26, 8): Unresolved reference: livekit
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (27, 8): Unresolved reference: livekit
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (89, 72): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (134, 8): Unresolved reference: JoinResponse
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (149, 8): Unresolved reference: JoinResponse
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (167, 41): Unresolved reference: JoinResponse
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (250, 15): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (251, 18): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (251, 55): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (252, 8): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (258, 16): Not enough information to infer type variable T
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (452, 47): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (466, 56): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (500, 42): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (502, 13): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (503, 13): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (535, 32): Unresolved reference: JoinResponse
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (535, 46): Unresolved reference: ReconnectResponse
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (600, 30): Unresolved reference: forceRelay
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (600, 44): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (614, 38): Unresolved reference: JoinResponse
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (616, 48): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (617, 51): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (619, 34): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (620, 47): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (621, 46): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (622, 34): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (622, 66): Unresolved reference: LivekitModels
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (623, 52): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (624, 64): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (625, 74): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (629, 55): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (702, 61): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (705, 13): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (712, 13): Unresolved reference: LivekitRtc
/livekit/livekit-android-sdk/src/main/java/io/livekit/android/room/RTCEngine.kt: (717, 50): Unresolved reference: LivekitRtc

**Comment by davidliu** [comment]
If you're trying to compile the SDK locally, please follow the [dev instructions](https://github.com/livekit/client-sdk-android#dev-environment).

**Comment by Oliver-WJ** [comment]
> If you're trying to compile the SDK locally, please follow the [dev instructions](https://github.com/livekit/client-sdk-android#dev-environment).

It has nothing to do with this

**Comment by Oliver-WJ** [comment]
> > If you're trying to compile the SDK locally, please follow the [dev instructions](https://github.com/livekit/client-sdk-android#dev-environment).
> 
> It has nothing to do with this

emm ~~  That's true,thank you
