### ISSUE TITLE
Blur SurfaceViewRenderer

### ISSUE THREAD

**Issue by codelab-sahil** [livekit/client-sdk-android#229]
Hello, @davidliu 

I need to set blur effect to **SurfaceViewRenderer** for 1 or 2 mins in between of video streaming. Is it possible to give that effect?

**Comment by davidliu** [comment]
This isn't a functionality we support nor plan to support directly. You can get the video frames and blur them yourself before passing them to the SurfaceViewRenderer though.

**Comment by safeer-ahmed** [comment]
@davidliu do you mean that we need to customise the VideoSink as discussed in [ this issue also](https://github.com/livekit/client-sdk-android/issues/341)?

If that's the case then how the blurred bitmap can be displayed on the local `SurfaceViewRenderer` and also how this blurred bitmap will be streamed to other call participants?

```
class CustomVideoSink(private val surfaceViewRenderer: SurfaceViewRenderer) : VideoSink {

        override fun onFrame(videoFrame: VideoFrame) {

                // How can this modified bitmap be shown as a videoFrame and also streamed to others?
                val bitmap = videoFrame.buffer.toI420()?.toBitmap()

                surfaceViewRenderer.onFrame(videoFrame)
           
        }
    }
