### ISSUE TITLE
adding a VideoTrack to a view where the screen is not visible does not play the video properly

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-android#230]
Hello,

Like the issue title, I encountered this problem when using HorizontalScrollView. Add SurfaceViewRenderer to his subview. If there are multiple subviews (multiple VideoTracks), SurfaceViewRenderer plays the video normally within the visible range of the screen, but when it exceeds In the view of the screen, SurfaceViewRenderer cannot play normally.

hope you can help me.

Thank you!

**Comment by wzJun1** [comment]
Replenish:

1. "Won't play normally" means: black screen

2. When `TrackSubscribed` is received, we get the VideoTrack and call addRenderer, and then slide the HorizontalScrollView quickly, so that the last view in the HorizontalScrollView can be quickly displayed on the mobile phone screen. At this time, the last SurfaceViewRenderer can be normal play.

**Comment by davidliu** [comment]
Do you mean for example, if the video view starts off screen, and then is scrolled on screen later, the view doesn't start playing?

**Comment by wzJun1** [comment]
> Do you mean for example, if the video view starts off screen, and then is scrolled on screen later, the view doesn't start playing?

可以理解为: 当SurfaceViewRenderer或TextureViewRenderer显示在屏幕外，但并不是隐藏，仅仅是不在屏幕内的时候（HorizontalScrollView），我们在调用addRenderer之后，等一会或者等几秒钟再去滑动视图让他显示在屏幕内，那么SurfaceViewRenderer将是黑屏的，但是音频流是正常播放的。

如果在addRenderer之后迅速把视图滑动到SurfaceViewRenderer，让他出现在屏幕内，这时候将会等一会，可能是100-500ms之后，正常播放视频。

**Comment by wzJun1** [comment]
> Do you mean for example, if the video view starts off screen, and then is scrolled on screen later, the view doesn't start playing?

what you said is exactly what happened to me

**Comment by wzJun1** [comment]
I found that when SurfaceViewRenderer appeared on the screen, I called addRenderer again, and the video was displayed normally.

But this situation is theoretically not normal

**Comment by davidzhao** [comment]
did you turn on `adaptiveStream`?

**Comment by wzJun1** [comment]
That's right, I set `adaptiveStream` to true earlier.

It turned out to be the reason, now I set it to false and everything works fine.

Thank you.

**Comment by wzJun1** [comment]
But I read `docs.livekit.io`'s introduction to `adaptiveStream`, and there is a sentence like this:

"which pauses the associated track until the element's visibility is restored."

When I swipe the ScrollView, a view outside the screen appears on the screen. At this time, the view should be visible (this refers to being visible to the naked eye, not manually setting `visibility`), but the track has not been restored.

**Comment by davidzhao** [comment]
Thank you for the report. It turns out to be a bug with adaptiveStream. We were able to address it and will cut a new release shortly!

**Comment by wzJun1** [comment]
> Thank you for the report. It turns out to be a bug with adaptiveStream. We were able to address it and will cut a new release shortly!

That's great, it was processed quickly, and it solved my urgent need, thank you!
