### ISSUE TITLE
Failed to transform 'C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.68\46a080368d38b428d237a59458f9bc915222894d\bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)

### ISSUE THREAD

**Issue by ChenMoGe2** [livekit/client-sdk-android#24]
Android Studio:4.0.2
jdk:1.8
gradle:7.0.2

When I generate release apk of sample app,the console send mistake "Failed to transform 'C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.68\46a080368d38b428d237a59458f9bc915222894d\bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)"

and how to solve this,Thank you

**Comment by davidliu** [comment]
We probably don't need jetifier here, so I'll see if we can safely disable it.

Until then, you can try using the solution found here: https://github.com/grpc/grpc-java/issues/8264#issuecomment-863015607

**Comment by ChenMoGe2** [comment]
> We probably don't need jetifier here, so I'll see if we can safely disable it.
> 
> Until then, you can try using the solution found here: [grpc/grpc-java#8264 (comment)](https://github.com/grpc/grpc-java/issues/8264#issuecomment-863015607)

I success using solution in grpc/grpc-java#8264 (comment) and it success,thank you very much!
