### ISSUE TITLE
Audio Quality Issues of Voice Calls Compared to Google Meet

### ISSUE THREAD

**Issue by Drengel1990** [livekit/client-sdk-android#240]
Good day. Faced with the problem that it is difficult to hear what other users are saying. For example, we compared Google Meet and the sound quality is much better. Is there a way to improve this programmatically?

**Comment by Drengel1990** [comment]
I mean using a pure voice channel. Not a video

**Comment by davidzhao** [comment]
Unless we are able to hear the audio clip, it's not possible to determine if what you are running into is expected or not.

**Comment by davidliu** [comment]
Closing as stale.

**Comment by davidzhao** [comment]
Possibly related to #264, please try the new release in a few days and increasing publishing bitrate.
