### ISSUE TITLE
Earpiece option not visible

### ISSUE THREAD

**Issue by harshilhp** [livekit/client-sdk-android#251]
**Describe the bug**
While in call when user connect wired headset Earpiece is removed from list.
Earpiece is not visible in list even if wired headset is removed at that time only speakerphone option is visible.

**To Reproduce**
1. Connected in room
2. Connected wired headset in device (Earpiece is removed from list as expected)
3. Removed wired headset from device (Earpiece is not there in list)

**Expected behavior**
Earpiece option should be added again after removing wired headset from device 

**Screenshots**
![list](https://github.com/livekit/client-sdk-android/assets/127843804/bb362d4a-3014-435d-b7fe-3c8bdf105319)
![view](https://github.com/livekit/client-sdk-android/assets/127843804/3cc26aa4-2db5-4b77-b45c-d67afad2ac37)

**Device Info:**
I think it is not device specific issue i checked in few devices and they all have same issue
 - Device: OnePlus Nord CE 3 Lite 5G
 - OS: Android 13
 - LiveKit SDK version: 1.2.1

**Comment by usayplz** [comment]
2 reasons: 
1. if userSelectedAudioDevice = Earpiece 
it does not check in onDeviceConnected.

com.twilio.audioswitch.AbstractAudioSwitch
override fun onDeviceConnected(audioDevice: AudioDevice) {
        this.logger.d(TAG_AUDIO_SWITCH, "onDeviceConnected($audioDevice)")
        if (audioDevice is Earpiece && this.availableAudioDevices.contains(WiredHeadset())) {
            return
        }
        val wasAdded = this.availableUniqueAudioDevices.add(audioDevice)
        if (audioDevice is WiredHeadset) {
            this.availableUniqueAudioDevices.removeAll { it is Earpiece }
        }
        this.selectAudioDevice(wasListChanged = wasAdded)
    }

2. After wiredhandset disconnected Earpiece never add back. Because of "wasChanged = true" condition does not execute: this.availableUniqueAudioDevices.add(Earpiece())


com.twilio.audioswitch.AudioSwitch
override fun onDeviceDisconnected(audioDevice: AudioDevice) {
        this.logger.d(TAG_AUDIO_SWITCH, "onDeviceDisconnected($audioDevice)")
        var wasChanged = this.availableUniqueAudioDevices.remove(audioDevice)
        if (this.userSelectedAudioDevice == audioDevice) {
            this.userSelectedAudioDevice = null
        }

        if (audioDevice is WiredHeadset && this.audioDeviceManager.hasEarpiece()) {
            wasChanged = wasChanged || this.availableUniqueAudioDevices.add(Earpiece())
        }
        this.selectAudioDevice(wasChanged)
    }

**Comment by davidliu** [comment]
Have a fix coming soon.
