### ISSUE TITLE
 android.opengl.GLException:Failed to create EGL context: 0x3000

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-android#258]
**Describe the bug**

My LiveKit runs in a separate activity. When I open the calling activity multiple times, the following error will occur. If this situation occurs, I will not be able to make calls unless I exit the entire app process:

```
android.opengl.GLException:Failed to create EGL context: 0x3000
```

It feels like the Eglcontext has not been released.

But I have already done the following in onDestroy.

```
room.disconnect()
room.release()
```

I have calculated that after approximately 20-30 normal calls, this situation will occur.

**To Reproduce**

After approximately multiple or (20-30) normal calls, this situation will occur

**Device Info:**
 - Device:  ALL 
 - OS: Android 12
 - LiveKit SDK version: 1.2.2

**Comment by wzJun1** [comment]
this is my sdk configuration:

```
val options = RoomOptions(
    adaptiveStream = false,
    dynacast = false,
    audioTrackCaptureDefaults = LocalAudioTrackOptions(
        noiseSuppression = true,
        echoCancellation = true,
        autoGainControl = true,
        highPassFilter = true,
        typingNoiseDetection = true,
    ),
    videoTrackCaptureDefaults = LocalVideoTrackOptions(
        position = CameraPosition.FRONT,
        captureParams = VideoPreset169.VGA.capture,
    ),
    audioTrackPublishDefaults = AudioTrackPublishDefaults(
        audioBitrate = 20_000,
        dtx = false,
    ),
    videoTrackPublishDefaults = VideoTrackPublishDefaults(
        videoEncoding = VideoPreset169.VGA.encoding,
        videoCodec = VideoCodec.VP8.codecName
    )
)

//初始化聊天房间配置
room = LiveKit.create(
    applicationContext,
    overrides = LiveKitOverrides(
        audioHandler = audioHandler
    ),
    options = options
)
```

**Comment by wzJun1** [comment]
The exception was thrown by 'initVideoRenderer'

**Comment by fiather** [comment]
I also have the same error as above. Even if the initVideoRenderer exception is processed, an error occurs at the end.

kgsl-3d0: KGSL active contexts:
kgsl-3d0: pid           process         total    attached   detached
kgsl-3d0: 16606    X.x.x.xx.x            201      201        0

**Comment by fiather** [comment]
I seem to have solved it. This was not a livekit problem, it was my problem.

**Comment by wzJun1** [comment]
> I seem to have solved it. This was not a livekit problem, it was my problem.

How to solve it?

**Comment by fiather** [comment]
I think you would have used textViewRenderer or surfaceViewRenderer.

Did you call  the release of the renderer after using the renderer?

And you have to check the log of kgsl

**Comment by fiather** [comment]
You can see the text about release of the renderer in TextureViewRenderer.kt

**Comment by wzJun1** [comment]
> I think you would have used textViewRenderer or surfaceViewRenderer.
> 
> Did you call the release of the renderer after using the renderer?
> 
> And you have to check the log of kgsl

Yes, as you said.

Now I will use TextureViewRenderer and try to call release.

thx!

**Comment by wzJun1** [comment]
@fiather 
@davidliu 
> You can see the text about release of the renderer in TextureViewRenderer.kt

I used RecyclView, and even if I called release(), this error still occurs. Is there a solution or sample code to refer to?
