### ISSUE TITLE
Could not find com.github.webrtc-sdk:android:92.4515.02

### ISSUE THREAD

**Issue by Yehsam23** [livekit/client-sdk-android#27]
I use the version 0.7.0
implementation "io.livekit:livekit-android:0.7.0"

The log:
Could not find com.github.webrtc-sdk:android:92.4515.02.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/webrtc-sdk/android/92.4515.02/android-92.4515.02.pom
       - https://jcenter.bintray.com/com/github/webrtc-sdk/android/92.4515.02/android-92.4515.02.pom

**Comment by davidliu** [comment]
Hi, I believe that dependency is distributed through jitpack. You'll want to add `maven { url 'https://jitpack.io' }` to the list of repositories for your project.

It may look something like this:

```
subprojects {
    repositories {
        google()
        mavenCentral()
        // ...
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by Yehsam23** [comment]
Thanks it fixed
