### ISSUE TITLE
if both parties choose to turn on the speaker: Speakerphone, there will be loud noise

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-android#271]
**Describe the bug**

if both parties choose to turn on the speaker: Speakerphone, there will be loud noise.

The same problem occurs in `sample-app`, even if the distance is far.

but this is not the case in version 1.2.0.

**To Reproduce**
1. Select Audio Device: Speakerphone
 
**Device Info:**
 - Device: ALL
 - OS: [e.g. Android 12]
 - LiveKit SDK version: 1.2.2 - 1.4.0

**Comment by davidliu** [comment]
Are you talking about two speakerphones close by, causing microphone feedback?

**Comment by wzJun1** [comment]
@davidliu 

No, they are not close. The distance between the two mobile phones may be 10-15 meters. There will still be obvious noise and loud sound as long as both parties turn on the speakers.

When I tested it in the sample App, I also found the same problem.

**Comment by davidzhao** [comment]
This is expected.. echo cancellation cannot cancel feedback from another device nearby.

That is a limitation of audio stack on mobile devices today.

**Comment by wzJun1** [comment]
> This is expected.. echo cancellation cannot cancel feedback from another device nearby.
> 
> That is a limitation of audio stack on mobile devices today.

Why doesn't 1.2.0 have this problem?

At the same distance, the version only changed from 1.2.0 to 1.4.0

**Comment by davidzhao** [comment]
interesting, does 1.2.0 not show any feedback at all? There are quite a few changes since then. Some are related to the audio stack.

Which audio mode are you using?

**Comment by wzJun1** [comment]
@davidzhao 

No parameters are given, everything is default

**Comment by wzJun1** [comment]
I have tested that the sample App of 1.2.0 and the sample App of 1.4.0 can be reproduced without modifying anything. You can test it by running it directly and turning on the speaker.

https://github.com/livekit/client-sdk-android/tree/main/sample-app

**Comment by mayurappscripde** [comment]
Facing same issue

**Comment by mayurappscripde** [comment]
It will work normal if you set  `audioOutputType = AudioType.MediaAudioType()`

**Comment by wzJun1** [comment]
> It will work normal if you set ` audioHandler.audioMode = AudioManager.MODE_NORMAL`. here default mode is `MODE_IN_COMMUNICATION`. it cause an issue

Really? I'll give it a try, thank you

**Comment by initpwn** [comment]
Any update on this? 
We're facing the same issue. Both parties are distant, getting loud noise on speaker mode.

**Comment by wzJun1** [comment]
@mayurappscripde @initpwn @davidzhao 

Invalid.

I reset `audiomode` = AudioManager.MODE_NORMAL, it doesn't work. noise still loud.

I found that the android demo also has this issue, Including the latest version 1.5.3, haven't the staff noticed it?

> It will work normal if you set ` audioHandler.audioMode = AudioManager.MODE_NORMAL`. here default mode is `MODE_IN_COMMUNICATION`. it cause an issue

**Comment by wzJun1** [comment]
fixed by 1.6.0 [#298 ](https://github.com/livekit/client-sdk-android/issues/298)
