### ISSUE TITLE
Remote participant screen is often not output.

### ISSUE THREAD

**Issue by fiather** [livekit/client-sdk-android#280]
I need your help : )

i received TrackSubscribed from RoomEvent before addRenderer.
Nothing is displayed on the screen before the new addRenderer.

track = [(io.livekit.android.room.track.RemoteTrackPublication@c82b316, io.livekit.android.room.track.RemoteVideoTrack@b5c9e1d)] io.livekit.android.room.track.RemoteVideoTrack@b5c9e1d

I also checked that I received the track well and added TextureViewRenderer there. But sometimes nothing is displayed on the screen.

**Comment by fiather** [comment]
I think it has nothing to do with addRenderer.
Because after getting the track, I repeated removeRender and addRender for about 15 seconds.
However, nothing was displayed on the screen in the same way

It feels like Renderer is not starting.

**Comment by fiather** [comment]
i checked the onframe log of renderer. The onframe was still being called.
However, there seems to be no contents.

**Comment by wzJun1** [comment]
initVideoRenderer?

**Comment by fiather** [comment]
1. initVideoRenderer
2. if track != null  then track.addRenderer( TextureViewRenderer in xml )

I did both number 1 and number 2
Usually, remote video comes out well. Sometimes the remove video doesn't come out.

**Comment by davidliu** [comment]
Can you try and see if it repros on one of the sample apps as well? Or can you provide a repro code sample? It's hard to tell where the issue is here.

**Comment by fiather** [comment]
it's my problem!!!!!
thank you !!!!!! : )
