### ISSUE TITLE
How to publish screen sharing audio?

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-android#292]
I see the 'SCREEN_SHARE_AUDIO' parameter in TrackSource, but I really can't find a way to share the screen sound

Or maybe now that I've got the screen share sound, like buffer or something, how do I publish it?

**Comment by davidliu** [comment]
We don't support audio sources other than the microphone at the moment. We're looking to add in that functionality soon though.

**Comment by davidliu** [comment]
Implemented in v2.10.0 by #528.
