### ISSUE TITLE
How to replace the webrtc library by my own webrtc library? 

### ISSUE THREAD

**Issue by guanjw** [livekit/client-sdk-android#293]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guanjw** [comment]
I want the details, thanks

**Comment by guanjw** [comment]
If I get the webrtc library by compiling the origin code of google webrtc，is there any incompatible issue in api

**Comment by davidzhao** [comment]
that isn't supported. this SDK requires our fork
