### ISSUE TITLE
Audio transmitting and echo receiving from sample-app

### ISSUE THREAD

**Issue by navin-kumar-sheoran** [livekit/client-sdk-android#298]
**Describe the bug**
Audio Switch handler not working in Speakerphone Mode. 

**To Reproduce**
1. Build the app from `sample-app`
2. Join room with token from my livekit server
3. Switch audio to Speakerphone 
4. Getting echo of my own voice from other participant, if other participant mute himself, then echo not coming
5. Checked with other device, audio not transmitting to other participant when in Speakerphone but working well in earpiece/bluetooth mode

**Expected behavior**
It should work for Speakerphone too

**Device Info:**
 - Device: One plus Nord, Samsung M12
 - OS: Android 12
 - LiveKit SDK version: 1.4.2

**Additional context**
This issue happening when both devices are in different city.
Even i disabled E2EE, it's causing the same issue. 
Even tried with audio.mode = AudioManager.MODE_NORMAL

**Code Configuration**

```
val room = Livekit.create(
         appContext = application,
         options = RoomOptions(adaptiveStream = true , dynacast = true), 
         overrides = LiveKitOverrides(
                               audioOptions = AudioOptions(
                                    audioHandler = AudioSwitchHandler( context = application.applicationContext)
                                  )
          ),
)
```

```
room.connect(  url = url, token = token, 
            roomOptions = RoomOptions(e2eeOptions = getE2EEOptions()
)
```

Even I tried with below options : 

- When LocalAudioTrackOptions with value = false

```
val options = RoomOptions(
                        audioTrackCaptureDefaults = LocalAudioTrackOptions(
                              noiseSuppression = false,
                              echoCancellation = false,
                              autoGainControl = false,
                              highPassFilter = false,
                              typingNoiseDetection = false,
                                                                                                 ),
)
```
-  When LocalAudioTrackOptions with value = true

```
val options = RoomOptions(
                        audioTrackCaptureDefaults = LocalAudioTrackOptions(
                              noiseSuppression = true,
                              echoCancellation = true,
                              autoGainControl = true,
                              highPassFilter = true,
                              typingNoiseDetection = true,
                                                                                                 ),
)
```

**Comment by DandyLorenz** [comment]
I also encountered this problem. This is a major problem. I hope the noise problem will be fixed soon.

**Comment by Roman-hub** [comment]
We are also experiencing this problem.

**Comment by wzJun1** [comment]
> I also encountered this problem. This is a major problem. I hope the noise problem will be fixed soon.

+1

We also encountered the same problem.

It stands to reason that since this bug exists in `sample-app`, everyone should have encountered it. It is strange why there is no quick fix.

**Comment by davidliu** [comment]
Try version 1.6.0, this should now be fixed.

**Comment by wzJun1** [comment]
Yes, I'm sure he's been fixed, thanks

**Comment by navin-kumar-sheoran** [comment]
Thanks it worked
