### ISSUE TITLE
How to send customized video and audio?

### ISSUE THREAD

**Issue by liuyuan22** [livekit/client-sdk-android#299]
**Is your feature request related to a problem? Please describe.**
We have a small camera. The camera has a wifi module and provides an Android SDK. Our app uses the SDK to connect to the camera. The camera sends video and audio data through the SDK. How can I send this data through your SDK? Thanks~

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by davidliu** [comment]
Custom audio data can't be published at the moment. It's on our roadmap though.

Custom video data can be published by implementing `VideoCapturer` and passing frames through to the `capturerObserver.onFrameCaptured` callback.

**Comment by liuyuan22** [comment]
Ok thanks, where can I see your roadmap?

**Comment by hardenerdev** [comment]
Hi all!

As @liuyuan22, I'm really interested into this topic.
I hava an H264 stream within height, width, fps, frame data and pts. I really want to send it to a livekit deployed server.

Regarding the android sdk documentation, I am not able to find `VideoCapturer` and `capturerObserver.onFrameCaptured`.
Where can I find related documentation?

Thanks in advance! :blush:

**Comment by davidliu** [comment]
@hardenerdev That would be `org.webrtc.VideoCapturer`, and the `capturerObserver` is passed in the `initialize` method there.

https://github.com/livekit/client-sdk-android/blob/627ccca7ffb53f2cca2a7e540dbf06921b7f754e/livekit-android-sdk/src/main/java/io/livekit/android/room/track/video/BitmapFrameCapturer.kt

This is a simple implementation based on pushing bitmaps. You can try adapting it for your own purposes.

**Comment by Orienser** [comment]
@davidliu Hi, any updates on this? 
I have an IP camera that supports RTSP streaming. I‘m able to publish the video data to LiveKit, but can't find a way to publish the audio data.

**Comment by davidliu** [comment]
@Orienser sorry, no updates here.

**Comment by davidliu** [comment]
Implemented in v2.10.0 by #528.

**Comment by tuanpdPaditech** [comment]
@davidliu hi, I'm trying to send a custom video stream through LiveKit, but it seems the transmission hasn't been successful. Below is my code:

`package com.example.streaming_deepar.streaming

import android.graphics.Matrix
import android.os.Handler
import android.os.Looper
import android.util.Log
import livekit.org.webrtc.CapturerObserver
import livekit.org.webrtc.SurfaceTextureHelper
import livekit.org.webrtc.TextureBufferImpl
import livekit.org.webrtc.VideoCapturer
import livekit.org.webrtc.VideoFrame
import livekit.org.webrtc.VideoFrameDrawer
import livekit.org.webrtc.YuvConverter

class DeepARVideoCapturer(
) : VideoCapturer {
    lateinit var handler: Handler
    lateinit var yuvConverter: YuvConverter
    var capturerObserver: CapturerObserver? = null
    private var surfaceTextureHelper: SurfaceTextureHelper? = null

    override fun initialize(
        surfaceTextureHelper: SurfaceTextureHelper,
        context: android.content.Context,
        capturerObserver: CapturerObserver
    ) {
        Log.d("TAG-PT", "initialize")
        this.surfaceTextureHelper = surfaceTextureHelper
        this.capturerObserver = capturerObserver
        handler = Handler(Looper.getMainLooper())
        val videoFrameDrawer = VideoFrameDrawer()
        yuvConverter = YuvConverter(videoFrameDrawer)
    }

    override fun startCapture(width: Int, height: Int, framerate: Int) {
        Log.d("TAG-PT", "startCapture: $width - $height - $framerate")
        // Không làm gì ở đây, DeepARRenderer sẽ push frame theo cách thủ công.
        capturerObserver?.onCapturerStarted(true)
    }

    override fun stopCapture() {
        // Giải phóng surface nếu cần
    }

    override fun changeCaptureFormat(p0: Int, p1: Int, p2: Int) {

    }

    override fun isScreencast(): Boolean = false


    override fun dispose() {
        stopCapture()
    }

    fun sendFrame(
        textureWidth: Int,
        textureHeight: Int,
        textureId: Int,
        matrix: FloatArray
    ) {
        capturerObserver?.let {
            val timestampNs = System.nanoTime()

            val androidMatrix = Matrix()

            val matrix3x3 = floatArrayOf(
                matrix[0], matrix[4], matrix[12],
                matrix[1], matrix[5], matrix[13],
                matrix[3], matrix[7], matrix[15]
            )
            androidMatrix.setValues(matrix3x3)
            val buffer = TextureBufferImpl(
                textureWidth,
                textureHeight,
                VideoFrame.TextureBuffer.Type.OES,  // hoặc RGB tuỳ texture bạn dùng
                textureId,
                androidMatrix,
                handler,
                yuvConverter,
                null // releaseCallback nếu cần
            )
            val frame = VideoFrame(buffer, 0,  /* rotation */timestampNs)
            capturerObserver?.onFrameCaptured(frame)
            frame.release()

        }
    }

}`

With the code above, I’m not receiving any video—only audio is working. please help me
