### ISSUE TITLE
Can not connect when use VPN

### ISSUE THREAD

**Issue by Yehsam23** [livekit/client-sdk-android#3]
Hello,

I used Android SDK 0.6.5 to connect
I can connect under normal circumstances, but it fails after I turn on the VPN

Edited: I can use Google Meet & other WebRTC connection with my VPN
Use browser open "https://livekit.io/playground" success with VPN

The following is the connected Log 

Fail with VPN [fail.txt](https://github.com/livekit/client-sdk-android/files/6974061/fail.txt)
Success with NO VPN [success.txt](https://github.com/livekit/client-sdk-android/files/6974062/success.txt)

**Comment by davidzhao** [comment]
hi @Yehsam23 can you share how the server is configured? Does it have TURN set up? and which ports have you opened on the firewall?

**Comment by Yehsam23** [comment]
@davidzhao 
My test is connect to "wss://demo.livekit.io"
And i try android LiveKit sample, now working with my VPN.
When i turn off the VPN, i can connected.

BTW, iOS LiveKit doesn't have this issue with same VPN.

**Comment by davidzhao** [comment]
This might be due to Android SDK using an older WebRTC library. We'll investigate.

**Comment by davidzhao** [comment]
@Yehsam23 please reopen if this remains an issue. it should be resolved with WebRTC SDK updates.
