### ISSUE TITLE
Failed to resolve: com.github.davidliu:audioswitch:d18e3e31d427c27f1593030e024b370bf24480fd

### ISSUE THREAD

**Issue by mk1490** [livekit/client-sdk-android#303]
Failed to resolve: com.github.davidliu:audioswitch:d18e3e31d427c27f1593030e024b370bf24480fd
When project launch

**Comment by davidliu** [comment]
Did you add jitpack to your dependency repositories?

**Comment by mk1490** [comment]
Yes

**Comment by mk1490** [comment]
> Did you add jitpack to your dependency repositories?

Apparently, the problem is related to the version of the dependency "com.github.davidliu:audioswitch" which cannot find it!

**Comment by mk1490** [comment]
Will this problem be solved?

**Comment by davidliu** [comment]
Hmm, just tested, it finds it just fine. The files are still up here:

https://jitpack.io/com/github/davidliu/audioswitch/d18e3e31d427c27f1593030e024b370bf24480fd/

**Comment by davidliu** [comment]
Closing as there's nothing to be done here. Verified Jitpack is working and is still hosting the files. 

Ensure you're declaring the Jitpack maven repo as shown in the instructions.
