### ISSUE TITLE
Native Memory is increasing every time when app connect/disconnect a room

### ISSUE THREAD

**Issue by serrg1994** [livekit/client-sdk-android#305]
have an app which has to be ran on android 24/7 but I notices that sometimes is was killed by android. After some investigation I found that Android has memory limits for 1 app and it's 512Mb, heap size and memory class is 192Mb.
If found when my app connect/disconnect a room memory a little bit increases and in native stack in idle state it add about additional 1 - 2 mb. I ran LiveKit sample and found the same behaviour. Looks like there are some issues in WebRTC and memory leaks or it's normal behaviour

I was able to reproduce this issue, by using compose samle. Just was connecting disconnecting a call. I noticed every time it was increasing native memory usage a little bit, about 1 - 2 MB
![image](https://github.com/livekit/client-sdk-android/assets/9201885/9a46706c-ae59-46ed-8b67-1292fe4b03bf)

As my understanding all native memory has to be cleared and usage has to be the same before joining a call

**Device Info:**
 - Device: Sunchip RK3568
 - OS: Android 11
 - LiveKit SDK version: 1.4.2

**Comment by davidliu** [comment]
Closed by #306.
