### ISSUE TITLE
RoomEvent.ActiveSpeakersChange Speakers list not right

### ISSUE THREAD

**Issue by shoyu666** [livekit/client-sdk-android#311]
**Describe the bug**
Speakers list   include mute user  on the top。

**To Reproduce**
1. device A,B,C join room （no one was mute）,device A speak,Speakers list  return {A} 。
2. device A mute self，device B speak。 Speakers list  always return {A,B} 。
3.  unmute A，A speak，then B speak ,Speakers list  return {B,A} 。
4. See error **the problem is：** step2,when A is mute  Speakers list   include A on the top。

**Expected behavior**
Speakers list  not  include mute user  on the top。

**Screenshots**
user "f064@661-137
e-4fab-9128-e" is mute but Blue border does not disappear
<img src="https://github.com/livekit/client-sdk-android/assets/20290812/2e2dc81f-ade0-4d6a-a8d1-8dd503347ca8" width="300">

**Device Info:**
 - Device: [一加 Ace 2V] It seems to have nothing to do with the device
 - OS: [Android 13]
 - LiveKit SDK version: [1.2.1]
 

**Additional context**
- LiveKit Server version:[[v1.5.0](https://github.com/livekit/livekit/releases/tag/v1.5.0)] (Same issue running on windows,mac,linux)
- It may be a server side issue,i do not know。
- when mute A， JavaAudioDeviceModule.AudioRecordStateCallback  No more callbacks in device A。

**Comment by davidzhao** [comment]
this is the expected behavior.. ActiveSpeakersChanged returns any participant who's isSpeaking state has changed. It does not guarantee the first participant is currently speaking.

**Comment by davidzhao** [comment]
My mistake with the previous comment. I mis-interpreted the behavior there. This looks like potentially a server-side thing closing the android issue in favor of server-side https://github.com/livekit/livekit/issues/2228
