### ISSUE TITLE
Application randomly crashes when often connect/disconnect from the call multiple times in a row 

### ISSUE THREAD

**Issue by serrg1994** [livekit/client-sdk-android#314]
I noticed that my app is randomly crashing, so I started playing with it, and when I very quickly  and often connect/disconnect  a call app is crashing with next stack trace. I'm using latest 1.5.0 release and I know that it has memory leaks fixes where was fixed and one of the fixes was disposing peer connection instead of closing.
 
 Was able to reproduce it by calling device and when it joins a call just hand a call. It's not always happens, I have to try it multiple times to reproduce it.

<img width="878" alt="LiveKit crash" src="https://github.com/livekit/client-sdk-android/assets/9201885/a02b71f7-a268-4cc8-bd13-1db5519c8718">

**Comment by serrg1994** [comment]
Sometimes it's crashing with this error

<img width="1566" alt="Livekit_Crash_2" src="https://github.com/livekit/client-sdk-android/assets/9201885/03365ac6-c2b5-4fd3-ac5e-4545106da3c8">

**Comment by davidliu** [comment]
What version of the sdk is this using?
