### ISSUE TITLE
UnsatisfiedLinkError：No implementation found for long org.webrtc.SoftwareVideoEncoderFactory.nativeCreateFactory()

### ISSUE THREAD

**Issue by shoyu666** [livekit/client-sdk-android#320]
**Describe the bug**
exception:
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long org.webrtc.SoftwareVideoEncoderFactory.nativeCreateFactory() (tried Java_org_webrtc_SoftwareVideoEncoderFactory_nativeCreateFactory and Java_org_webrtc_SoftwareVideoEncoderFactory_nativeCreateFactory__)

**To Reproduce**
1. [update](io.livekit:livekit-android:1.2.1) > io.livekit:livekit-android:1.5.1

**Expected behavior**
no exception

**Screenshots**

**Device Info:**
 - Device: [一加 Ace 2v]
 - OS: [e.g. Android 12]
 - LiveKit SDK version: [e.g. 1.5.1]

**Comment by davidliu** [comment]
Are you trying to instantiate a VideoEncoderFactory prior to calling `LiveKit.create`? This will happen if the native library isn't loaded yet.

Try calling `LiveKit.init` first if you need to access it prior to the create method.

**Comment by davidliu** [comment]
Which version were you using prior to updating to 1.5.1? Can you also provide a stack trace?

**Comment by shoyu666** [comment]
thanks,call  init works. ( LiveKit.Companion.init(applicationContext);)

version:
1.2.1   > 1.5.1 

call stack:（java code）
LiveKitOverrides overrides = new LiveKitOverrides(client,
                    new SoftwareVideoEncoderFactory(),null, audioOptions, null);
room = LiveKit.Companion.create(APP.application.getApplicationContext(), roomOptions, overrides);
