### ISSUE TITLE
How to fix the camera streaming resolution?

### ISSUE THREAD

**Issue by zmf2022** [livekit/client-sdk-android#322]
I have cloesed the simulcast but it does not work, can you help me? thanks

**Comment by davidliu** [comment]
Not sure what you mean by "fix camera streaming resolution", but the capture parameters and publish parameters can be changed through `videoTrackCaptureDefaults` and `videoTrackPublishDefaults` in `RoomOptions` when calling `LiveKit.create`.

**Comment by zmf2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，已收到您的邮件，将尽快给您回复！
