### ISSUE TITLE
How to change Camera back to front

### ISSUE THREAD

**Issue by farsunset** [livekit/client-sdk-android#335]
`room.getLocalParticipant().setCameraEnabled(on);`

I can't find func to change Camera front to back.

**Comment by davidliu** [comment]
Change the `videoTrackCaptureDefaults` prior to use, or `LocalVideoTrack.switchCamera` if the camera is already turned on.

https://docs.livekit.io/client-sdk-android/livekit-android-sdk/io.livekit.android.room.track/-local-video-track/index.html#-105226560%2FFunctions%2F-885714121

**Comment by davidliu** [comment]
See our example here:
https://github.com/livekit/client-sdk-android/blob/a6280a6e84956ab817ce3d63e9f52be4101da79b/sample-app-common/src/main/java/io/livekit/android/sample/CallViewModel.kt#L298

**Comment by farsunset** [comment]
Thanks!!!

**Comment by farsunset** [comment]
first i call room.getLocalParticipant().setCameraEnabled(on);

 LocalTrackPublication publication = room.getLocalParticipant().getTrackPublication(Track.Source.CAMERA);

but get publication is return null
 what is reason?
