### ISSUE TITLE
Can't change room settings for videoTrackCaptureDefaults

### ISSUE THREAD

**Issue by billypap1** [livekit/client-sdk-android#344]
**Describe the bug**

Hi, I have integrated LiveKit Android SDK ("io.livekit:livekit-android:1.5.3") to my Android app but I have an issue setting the room settings. 

I have set the following settings: 

```
val roomOptions = RoomOptions(
     false,false,null,null, LocalVideoTrackOptions(false,null,CameraPosition.FRONT,
         VideoCaptureParameter(160,90,30)
     ),null, videoTrackPublishDefaults = VideoTrackPublishDefaults(
         VideoEncoding(800000,30),false,VideoCodec.VP9.codecName,null,
         BackupVideoCodec(VideoCodec.VP8.codecName,VideoEncoding(800000,30),false)
     )
 )

 val connectOptions = ConnectOptions(true,null,null,false,false,ProtocolVersion.v9)

 room.connect(
     url,
     tokenRoom!!,
     connectOptions,
     roomOptions
 )
```

As you can see in the code, I have set Video Dimensions to h90 -> 160x90 16:9 30fps.

In the room analytics (Dashboard) I get resolution of 960x720 with 1-1.5 mbps bitrate (our limit is set to 800.000Kbps).  It doesn't apply the settings that I set. I don't have any issue with other Livekit's SDKs (JS,iOS).

Is this a bug? 

**To Reproduce**
1. Use LiveKit Android SDK ("io.livekit:livekit-android:1.5.3")
2. Try to connect with the settings above.

**Expected behavior**
The resolution should be h90 and bitrate lower than 800.000kbps. **It seems like the default values don't change on set.**

**Device Info:**
 - Device: Samsung Galaxy A13
 - OS: Android 13
 - LiveKit SDK version: 1.5.3

**Comment by davidliu** [comment]
This was marked as completed; did it resolve itself?
