### ISSUE TITLE
Is there any way to start with a fixed resolution?

### ISSUE THREAD

**Issue by mhy-priv** [livekit/client-sdk-android#365]
need a fixed resolution(eg: 1080x1920) and bitrate, instead of resolution change based on available bandwidth.

**Comment by mhy-priv** [comment]
A solution found but for Chrome:

> https://groups.google.com/g/discuss-webrtc/c/3JXbvEfNYd0?pli=1

Can I set 'contentHint' of MediaStreamTrack to 'detail', to indicate "the track should be treated as if video details are extra important"?  I don't know if this feature has been supported yet.

> https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/contentHint

**Comment by davidliu** [comment]
This is controlled by the `adaptiveStream` option in RoomOptions. Just turn that to false (or leave it out since by default it's false).

**Comment by z00174311** [comment]
> This is controlled by the `adaptiveStream` option in RoomOptions. Just turn that to false (or leave it out since by default it's false).

I don't think this method work, and i have tried leave it out but still not work.

**Comment by zmf2022** [comment]
Do you solve it?

**Comment by Rayman230510** [comment]
I encountered the same problem.

**Comment by adrian-niculescu** [comment]
The LiveKit Android SDK does have configurations that can affect video resolution and quality based on available bandwidth. 

1. **Room Options**:
   - `adaptiveStream`: Manages the quality of subscribed video tracks based on the size of the video elements and their visibility.
   - `dynacast`: Dynamically pauses video layers that are not being consumed, reducing publishing CPU and bandwidth usage.

   ```kotlin
   var adaptiveStream: Boolean = false
   var dynacast: Boolean
       get() = localParticipant.dynacast
       set(value) {
           localParticipant.dynacast = value
       }
   ```

2. **Local Video Track Options**:
   - `videoEncoding`: Specifies the encoding parameters for video tracks.
   - `simulcast`: Support for simulcasting, which can optimize bandwidth usage.
   - `degradationPreference`: Indicates the preference between degrading resolution vs. framerate when bandwidth is constrained.

   ```kotlin
   data class VideoTrackPublishDefaults(
       override val videoEncoding: VideoEncoding? = null,
       override val simulcast: Boolean = true,
       override val videoCodec: String = VideoCodec.VP8.codecName,
       override val scalabilityMode: String? = null,
       override val backupCodec: BackupVideoCodec? = null,
       override val degradationPreference: RtpParameters.DegradationPreference? = null,
   ) : BaseVideoTrackPublishOptions()
   ```
