### ISSUE TITLE
Could you add Resuming/Resumed State for Room

### ISSUE THREAD

**Issue by usayplz** [livekit/client-sdk-android#380]
**Describe the bug**
Where is no way to know Room.State (reconnecting, resuming) when using ReconnectType.FORCE_SOFT_RECONNECT

**To Reproduce**
1. val room = LiveKit.create(appContext = context)
2. room.setReconnectionType(ReconnectType.FORCE_SOFT_RECONNECT)
3. room::state.flow.collect { state -> if (state == Room.state.RECONNECTING) { state.show() }}

**Expected behavior**
Please add existing reconnecting state or add new state resuming for Room.state

**Comment by davidliu** [comment]
`room.setReconnectType` is not meant for production use, and is only there for testing purposes. It's marked `@VisibleForTesting` for this very reason.
