### ISSUE TITLE
Support virtual backgrounds and background blur

### ISSUE THREAD

**Issue by jezell** [livekit/client-sdk-android#388]
This is a must have feature for 100% of video conferencing apps. It needs to be supported by the client SDK.

**Comment by davidliu** [comment]
We expose post-processing of the local video capture through the use of a `VideoProcessor`. There's an example integration with Selfie Segmentation here: 

https://github.com/livekit/client-sdk-android/tree/main/examples/selfie-segmentation

There aren't any plans to support this out of the box.

**Comment by jezell** [comment]
@davidliu that's weird, because @davidzhao just told me there were.

**Comment by davidzhao** [comment]
@jezell this is probably a miscommunication. I think you are both right!

Our goal with the core SDK is to make it *possible* to perform frame processing before publishing, so you can hook in different kinds of virtual bg/etc. For the virtual background processing itself, we chose to not include that capability in the core library as it would bloat the library size for those that don't need it.

It's also true that we need to make it easier to use these features. There are two ways we could move forward:
1. through example code snippets (like DL has provided)
2. through an additional library that users could pull in

Currently 1 is available in the [example](https://github.com/livekit/client-sdk-android/tree/main/examples/selfie-segmentation) DL pointed out. Does that work for your current needs? Would love to hear what you think.

**Comment by jezell** [comment]
@davidzhao well the problem is we are currently using the flutter SDK where none of this is possible at the moment and there are no samples on how to integrate any of this there. Was hoping getting this into the native SDKs more first class would help that flutter client could also enable this, maybe there is a better path? Something integrated like this would definitely be easier to use:

https://docs.agora.io/en/video-calling/enable-features/virtual-background?platform=android

I get not wanting to bloat the package, but it's fairly complicated stuff for the average livekit consumer while also being a showstopper for a lot of people. Doesn't make sense for everyone to have slight variations on the concept that they pull from an example. Maybe a base interface could be added to the package for camera effects without any extra bloat, and then another package could be provided as a standard package on each platform and you just set the interface to something not null to turn it on?

localParticipant.cameraProcessor = liveKitVirtualBackgroundProcessor

**Comment by wchest** [comment]
For anyone coming here to learn how to use background blur/background images with LiveKit, it looks like the following package makes this possible now: https://github.com/livekit/track-processors-js. Possible I'm misunderstanding this as we haven't implemented LiveKit yet, but wanted to share in case this addresses the issue.

**Comment by geoffcfchen** [comment]
> We expose post-processing of the local video capture through the use of a `VideoProcessor`. There's an example integration with Selfie Segmentation here:
> 
> https://github.com/livekit/client-sdk-android/tree/main/examples/selfie-segmentation
> 
> There aren't any plans to support this out of the box.

Hi @davidliu , I saw the Selfie Segmentation example for Android. Do you have any guidance or examples for implementing this in an Expo managed workflow? Or is this feature currently limited to Android native projects only? Thanks.

**Comment by geoffcfchen** [comment]
> So we got it working but eventually decided to go with these guys: https://effectssdk.ai/
> 
> Their feature set is great and the quality of the virtual background is high and works well.
> 
> They kindly put together for us some sample code on how to use their SDK with Livekit.io: https://github.com/EffectsSDK/livekit-js-integration/tree/main

Hi @mjgaylord, can this be implemented for Expo managed workflow project?

**Comment by twinsbox89** [comment]
We’ve added EffectsSDK support to the LiveKit Flutter client (iOS and Android):
https://github.com/EffectsSDK/livekit-client-sdk-flutter

We’ve also released an integration for Flutter-WebRTC:
https://github.com/EffectsSDK/flutter-webrtc
