### ISSUE TITLE
Android unpublishTrack not triggering an unpublished event on other clients

### ISSUE THREAD

**Issue by Yehsam23** [livekit/client-sdk-android#4]
When using the Android SDK, use 

`localParticipant.unpublishTrack(trackPublication.getTrack());`

Other iOS, Android, Web will not receive "Unsubscribe" notification

But use the same method in the iOS SDK, and you will receive notifications elsewhere

**Comment by davidzhao** [comment]
Do you see an offer that's sent from the client after this? I believe it needs to re-negotiate when this happens.

**Comment by Yehsam23** [comment]
If i use `trackPublication.setMuted(true);`

The log:
`V/SignalClient: sending request: mute {
      sid: "TR_LXexXXtcCW3u"
      muted: true
    }`

=======

Use `localParticipant.unpublishTrack(trackPublication.getTrack());`

The log:
`I/org.webrtc.Logging: CameraCapturer: Stop capture`
`I/org.webrtc.Logging: CameraCapturer: Stop capture: Nulling session`
`I/org.webrtc.Logging: Camera2Session: Stop camera2 session on camera 1 Camera2Session: Stop internal`
`I/org.webrtc.Logging: CameraCapturer: Stop capture done`
`I/org.webrtc.Logging: SurfaceTextureHelper: stopListening()`

I don't see any SignalClient log if remove track

**Comment by davidzhao** [comment]
that seems like a bug, we'll take a look!

**Comment by wzJun1** [comment]
> Looks like the Android Video track isn't closing the RTC sender somewhere properly, resulting the server not getting notified of the closing.

That's great, it was processed quickly, and it solved my urgent need, thank you!
