### ISSUE TITLE
ConcurrentModificationException of RemoteVideoTrack.

### ISSUE THREAD

**Issue by jinnyuri** [livekit/client-sdk-android#401]
**Describe the bug**
Sometime ConcurrentModificationException occurs, if multiple people exit a group call at the same time.
I apologize for the lack of detailed logs, but describe solution below.

**To Reproduce**
1. Make a group call.
2. Exit at same time.

**Expected behavior**
Exception not occurs.

**Screenshots**

**Device Info:**
 - Device: [e.g. Google Pixel 4] Galaxy S22, S23, etc.
 - OS: [e.g. Android 12] All versions
 - LiveKit SDK version: [e.g. 1.0.0] 2.1.1

**Additional context**
Same as VideoTrack, if we apply lock for sinkVisibilityMap of RemoteVideoTrack, we can avoid the exception.

**Comment by davidliu** [comment]
Whoops, forgot to lock this down when I did the video track changes. Thanks for filing the issue.
