### ISSUE TITLE
Whether it can support screen sharing and pass custom options?

### ISSUE THREAD

**Issue by wzJun1** [livekit/client-sdk-android#409]
[#LocalParticipant.kt#L150](https://github.com/livekit/client-sdk-android/blob/412ff44e12f2f48e165c16ad9963d168f45dfba2/livekit-android-sdk/src/main/java/io/livekit/android/room/participant/LocalParticipant.kt#L150)

Hello, can you add custom `LocalVideoTrackOptions` here?

Because we need to modify `captureParams`, but the default screen sharing `captureParams` value is: `VideoPreset169.H540.capture`

**Comment by davidliu** [comment]
Whoops, sorry about that. Will be fixed by #410.
