### ISSUE TITLE
Save real-time intercom audio locally

### ISSUE THREAD

**Issue by MiaoYan0906** [livekit/client-sdk-android#412]
Hello, I have a business scenario. I need to save the audio data between turning on the microphone and turning off the microphone when I am in real-time intercom. After obtaining the samples data, I will save the audio file to the local in wav format. The wav audio saved each time is 0kb. Am I getting my data right? Is there another way to handle this?
![image](https://github.com/livekit/client-sdk-android/assets/101235249/9ac88b79-1cd5-4730-b57c-7ebfd1604005)

When I found a Demo that can save audio and video in client-sdk-android, the following error was reported when I used the project sample-app-record-local：
![image](https://github.com/livekit/client-sdk-android/assets/101235249/d68a7f2c-e123-4fc0-9158-21f0d7201622)

How can I solve this problem?

**Comment by davidliu** [comment]
Can you check if the `samples.data.size` is non-zero? 

Can't really help with writing bytes to a wav file (don't really know too much about about the various audio formats), but you can save the bytes directly to disk, since the bytes are just PCM.
