### ISSUE TITLE
Duplicate class in modules jetified-protobuf-java-3.15.1 and jetified-protobuf-javalite-3.17.2

### ISSUE THREAD

**Issue by jarvislin** [livekit/client-sdk-android#42]
Hi

I got the error as bellow after integrated this client SDK.
Is there any way to solve this error?

Thank you.

```
Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.15.1 (com.google.protobuf:protobuf-java:3.15.1) and jetified-protobuf-javalite-3.17.2 (com.google.protobuf:protobuf-javalite:3.17.2)
Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules jetified-protobuf-java-3.15.1 (com.google.protobuf:protobuf-java:3.15.1) and jetified-protobuf-javalite-3.17.2 (com.google.protobuf:protobuf-javalite:3.17.2)
Duplicate class com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream found in modules jetified-protobuf-java-3.15.1 (com.google.protobuf:protobuf-java:3.15.1) and jetified-protobuf-javalite-3.17.2 (com.google.protobuf:protobuf-javalite:3.17.2)
Duplicate class com.google.protobuf.AbstractMessageLite$InternalOneOfEnum found in modules jetified-protobuf-java-3.15.1 (com.google.protobuf:protobuf-java:3.15.1) and jetified-protobuf-javalite-3.17.2 (com.google.protobuf:protobuf-javalite:3.17.2)
Duplicate class com.google.protobuf.AbstractParser found in modules jetified-protobuf-java-3.15.1 (com.google.protobuf:protobuf-java:3.15.1) and jetified-protobuf-javalite-3.17.2 (com.google.protobuf:protobuf-javalite:3.17.2)
...
```

---
Android Studio Arctic Fox | 2020.3.1 Patch 3

`app/build.gradle`
```
dependencies {
    implementation 'io.livekit:livekit-android:0.8.0'
}
```

`settings.gradle`
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        jcenter() // Warning: this repository is going to shut down soon
    }
}
rootProject.name = "Livekit"
include ':app'
```

**Comment by davidliu** [comment]
I created a completely empty project containing only the livekit dependency, and it doesn't raise this error. Do you have other dependencies? Can you post the full list of dependencies you use?

For a workaround, you can probably exclude protobuf-javalite using this [workaround](https://stackoverflow.com/questions/56811328/duplicate-classes-error-after-adding-dialogflow-dependency-to-my-android-app/56947231#56947231).

**Comment by jarvislin** [comment]
Hi @davidliu 

Thanks for the reply.

I found this SDK conflict with latest Firebase SDKs.
The error message disappeared after I downgraded the Firebase SDKs.

**Comment by davidzhao** [comment]
@davidliu should we post the workaround in the README somewhere? It seems that firebase is a pretty common package for people to include.

**Comment by rourkepoulton99** [comment]
It just means that you have got conflicting depencies either from firebase or a different group. Whatever you do, do not exclude protobuf because that will cause your app to crash or not work. Instead try and remove the conflicting depency
