### ISSUE TITLE
Master cannot run

### ISSUE THREAD

**Issue by mengxiabing** [livekit/client-sdk-android#425]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info:**
 - Device: [e.g. Google Pixel 4]
 - OS: [e.g. Android 12]
 - LiveKit SDK version: [e.g. 1.0.0]

**Additional context**
![image](https://github.com/livekit/client-sdk-android/assets/18475448/08cabc59-b970-41bf-a022-5d44739e4a94)

**Comment by mengxiabing** [comment]
![image](https://github.com/livekit/client-sdk-android/assets/18475448/3e262ff6-d098-4890-82ec-173fbc2b0bdc)

**Comment by davidliu** [comment]
You don't have the protocol submodule installed. Make sure you follow the Dev Environment instructions in the readme.
