### ISSUE TITLE
Attempting soft reconnect, Attempting full reconnect, Error during reconnection.

### ISSUE THREAD

**Issue by User-Admin** [livekit/client-sdk-android#433]
**Describe the bug**
Attempting soft reconnect.
Closing SignalClient: code = 1000, reason = Starting new connection
websocket failure: null
Error during reconnection.
websocket closing

**Expected behavior**
When I use the Demo, use the cellular network data, normally connected to the room, during the connection process, the cellular network is always normal state. But all of a sudden it's Attempting soft reconnect. Then start the reconnection process, sometimes the reconnection can be successful, sometimes the reconnection fails, and the connection will not be connected again，what can be the cause of this，This disconnection issue also occurs when I use other versions of the SDK, whether I'm connecting to WIFI or using cellular data

**Screenshots**
![11](https://github.com/livekit/client-sdk-android/assets/18547391/fcb3db69-19f3-4428-b6cf-18990fc96cc1)
![12](https://github.com/livekit/client-sdk-android/assets/18547391/a0069b3a-5682-4de6-ae35-437a77eb47fd)
![13](https://github.com/livekit/client-sdk-android/assets/18547391/da569643-ac15-472b-8b11-2ff8ec80bc24)

**Device Info:**
 - Device: [e.g. Google Pixel 4]
 - OS: [e.g. Android 12]
 - LiveKit SDK version: [e.g. 2.4.0]

**Comment by davidliu** [comment]
Sounds like your internet connection isn't stable? We try to reconnect multiple times, but if none of them work, it eventually fails out and stops trying.
