### ISSUE TITLE
share screen sound

### ISSUE THREAD

**Issue by StephenChow-beep** [livekit/client-sdk-android#434]
How do I share screen sound? SCREEN_SHARE_AUDIO cannot be used.

**Comment by davidliu** [comment]
At the moment, this isn't possible.

**Comment by StephenChow-beep** [comment]
> 目前这还不可能。


Will this feature be added in the future? I currently cannot implement this function by modifying the source code, and the native method cannot achieve it.

**Comment by davidzhao** [comment]
yeah, it'll be possible soon. we already have the capability of feeding in raw audio bytes from the libwebrtc side. (currently available in Rust, python, and node). it'll take a bit of effort to open that path up for our client SDKs

**Comment by davidliu** [comment]
Implemented in v2.10.0 by #528.
