### ISSUE TITLE
 Unable to read Kotlin metadata due to unsupported metadata kind: kotlinx.metadata.jvm.KotlinClassMetadata$SyntheticClass@7bd5f84a.         public static final class DefaultImpls {

### ISSUE THREAD

**Issue by Sam53534512** [livekit/client-sdk-android#444]
when i run sample-app-compos Unable to read Kotlin metadata due to unsupported metadata kind: kotlinx.metadata.jvm.KotlinClassMetadata$SyntheticClass@7bd5f84a.
        public static final class DefaultImpls {

**Comment by Sam53534512** [comment]
<img width="1560" alt="WeChat1b0910682214047a54199280831862fa" src="https://github.com/livekit/client-sdk-android/assets/100915011/31ccbd2e-5088-4745-9917-809838076647">

**Comment by davidliu** [comment]
If you wish to run the sample apps directly from this repo, please consult the [Dev Environment instructions](https://github.com/livekit/client-sdk-android#dev-environment).
