### ISSUE TITLE
consider changing EventListenable.collect to return Nothing

### ISSUE THREAD

**Issue by weefbellington** [livekit/client-sdk-android#457]
[SharedFlow.collect](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/collect.html) function specifies Nothing as its return type. This is helpful for preventing errors, since the linter can mark any code after `collect` as unreachable.

Consider changing the EventListenable.collect extension function to match.

See also this issue: https://github.com/Kotlin/kotlinx.coroutines/issues/2789

**Comment by davidliu** [comment]
Thanks for the heads up! Will do.
