### ISSUE TITLE
Is there any tutorial that can guide webRTC compilation

### ISSUE THREAD

**Issue by shoyu666** [livekit/client-sdk-android#461]
Is there any tutorial that can guide webRTC compilation  (guide or script)
i just want to add key log when dev，Help identify issues with my program
Confused about how to obtain the corresponding version (125.6422.02) of the code (https://webrtc.googlesource.com/src)
thanks very much

**Comment by davidzhao** [comment]
We use our own fork of WebRTC [here](https://github.com/webrtc-sdk/webrtc)

build scripts can be found in [this repo](https://github.com/webrtc-sdk/webrtc-build)
