### ISSUE TITLE
Virtual Background for user video track

### ISSUE THREAD

**Issue by ashifali3147** [livekit/client-sdk-android#480]
I've developed a meeting app using LiveKit, and it's working well. Now, I'd like to add a feature that allows users to apply virtual backgrounds in our video, similar to what is available in Google Meet and Zoom. Is this possible?

**Comment by davidliu** [comment]
You can check out our example using [Selfie Segmentation](https://developers.google.com/ml-kit/vision/selfie-segmentation) here:

https://github.com/livekit/client-sdk-android/tree/main/examples/selfie-segmentation/src/main/java/io/livekit/android/selfie

We don't provide out of the box solutions for virtual backgrounds at this time.
