### ISSUE TITLE
SelfieBitmapVideoProcessor Not Receiving Frames in LiveKit 2.8.0

### ISSUE THREAD

**Issue by Jack-Android-93** [livekit/client-sdk-android#494]
**Describe the bug**
I encountered an issue when upgrading from LiveKit version 2.2.0 to 2.8.0 where the **SelfieBitmapVideoProcessor** stops receiving video frames for processing. This issue is specifically noticed in the onFrameCaptured(frame: VideoFrame) method, where no frames are being passed for further processing.

Details: Upon further investigation, I found that in the overridden method:
override fun onFrameCaptured(frame: VideoFrame?, parameters: VideoProcessor.FrameAdaptationParameters?)
The parameters object has incorrect values:
- drop is set to true
- scaleWidth and _scaleHeight_ are both 0

These incorrect values prevent frames from being processed correctly. Notably, this issue does not occur in version 2.2.0, where all frames and parameters are handled as expected.

**To Reproduce**

1. Upgrade LiveKit from version 2.2.0 to 2.8.0.
2. Implement a custom video processor using SelfieBitmapVideoProcessor.
3. Override the onFrameCaptured(frame: VideoFrame) method.
4. Observe that no frames are passed to this method.

**Expected behavior**
The onFrameCaptured method should receive valid VideoFrame objects for processing, with correct FrameAdaptationParameters.

**Workaround**
Reverting to LiveKit version 2.2.0 resolves the issue, with frames being processed correctly.

**Request for Assistance**
I would like to know if there are any updates or changes needed to ensure compatibility with LiveKit 2.8.0. How can I modify my implementation to correctly handle video frames using SelfieBitmapVideoProcessor in the latest version?

**Device Info:**
 - Device:  Samsung Note 10 Plus (Model SM-N976N)
 - OS: Android 12
 - LiveKit SDK version: 2.8.0

**Screen shoot**
<img width="1290" alt="Screen Shot 2024-09-02 at 1 20 17 AM" src="https://github.com/user-attachments/assets/abc857d4-8903-4618-a3e2-4e62acb41519">

**Comment by davidliu** [comment]
So, it looks like an upstream change altered the behavior so that the VideoProcessor is active only when the Room is connected (hence `drop` being true). If you're only using the VideoProcessor while connected, then it should continue to work as intended. I'll upload a fix to the selfie example app so that you can use the VideoProcessor while unconnected.

**Comment by davidliu** [comment]
Added a `NoDropVideoProcessor` that can handle unconnected processing. Inherit from that instead of `VideoProcessor` directly. There was also another bug that prevented processed frames from rendering locally that was fixed.

**Comment by Genening** [comment]
@Jack-Android-93 Hi, friend, I want to deal with the frame processor, I want to add a processor just like your sefie processor, however I don't know how to add the processor back to the project. I will really appreciate if you can help me, your project just as the same way I want to do, I develop a android app with react native. Or can you share the github link for your project, I can learn from your code, if your project is open source. Big thanks!
