### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by r-bird** [livekit/client-sdk-android#5]
## Steps to reproduce

1. `git clone git@github.com:livekit/client-sdk-android.git`
2. open project in Android Studio
3. sync project with gradle files
4. build sample-app

## Found issues

- [ ] `jCenter()` is deprecated, could be replaced with `mavenCentral()`
- [ ] `api 'org.webrtc:google-webrtc:1.0.32006'` is outdated, because binaries are no longer distributed to `https://dl.bintray.com/google/webrtc`
  - [ ] Could be replaced with `implementation fileTree(dir: 'libs', include: ['google-webrtc-*.aar'])`
  - downloaded from http://estigia.lsi.us.es:1681/artifactory/libs-release/org/webrtc/google-webrtc/1.0.32006/

Still results in `Task :livekit-android-sdk:compileDebugKotlin FAILED` due to various unresolved references.

**Comment by davidliu** [comment]
Build seems to be working fine here, could you post the full log of what's happening?

jCenter is deprecated, but not all artifacts have migrated to mavenCentral yet, so we're holding off on that (webrtc is still available through jCenter, for example).

We have plans to migrate to an updated version of the webrtc library soon though.

**Comment by r-bird** [comment]
There is basically one import error in the `livekit-android-sdk` project:
```
Unresolved reference: livekit
```

Maybe you have a matching library that is imported with this line in `sample-app/build.gradle`:
```
implementation fileTree(dir: 'libs', include: ['*.jar'])
```

**Comment by davidliu** [comment]
Do you have the [protocol repo](https://github.com/livekit/protocol) checked out and existing at the same top level directory?

**Comment by r-bird** [comment]
Ah, okay. It was checked out _in_ the top level directory. Now it's working.
