### ISSUE TITLE
The app fails after a few seconds of background audio collection (Android 14)

### ISSUE THREAD

**Issue by Yptake** [livekit/client-sdk-android#505]
In the Android 14 version, the app paused audio collection in the background and returned to the foreground before the audio was available again. How to handle this situation?

**Comment by davidliu** [comment]
On Android 14, a foreground service is required to use the microphone in the background. You can read up about it here:

https://developer.android.com/about/versions/14/changes/fgs-types-required#microphone

You can refer to our example code which has a simple implementation that has all you need to deal with this:

1. Declare your foreground service with the appropriate service types and permissions:

https://github.com/livekit/client-sdk-android/blob/main/sample-app-common/src/main/AndroidManifest.xml

2. Implement your foreground service:

https://github.com/livekit/client-sdk-android/blob/main/sample-app-common/src/main/java/io/livekit/android/sample/service/ForegroundService.kt

3. Start/stop your foreground service as needed:

https://github.com/livekit/client-sdk-android/blob/bcb54c68f23bf268e71ff3edf59c62b5a74bdc7b/sample-app-common/src/main/java/io/livekit/android/sample/CallViewModel.kt#L201-L206

https://github.com/livekit/client-sdk-android/blob/bcb54c68f23bf268e71ff3edf59c62b5a74bdc7b/sample-app-common/src/main/java/io/livekit/android/sample/CallViewModel.kt#L337-L338
