### ISSUE TITLE
Audio weak network situation

### ISSUE THREAD

**Issue by Yptake** [livekit/client-sdk-android#509]
Is there any way to optimize audio when the network is not in good condition (v2.8.0)

**Comment by davidliu** [comment]
Don't think there's anything that can be done here, audio streaming is already requires very little bitrate, and we prioritize audio over video server-side. You can try lowering the bitrate even more with the `AudioTrackPublishOptions`, but I don't think that will significantly improve things.

**Comment by Yptake** [comment]
thinks

**Comment by Yptake** [comment]
Thank you for your answer
