### ISSUE TITLE
Version 2.9.0, released yesterday, needs to be fixed.

### ISSUE THREAD

**Issue by sokolyaka** [livekit/client-sdk-android#519]
**Describe the bug**
Hi there!
Unfortunately, version 2.9.0, released yesterday, needs to be fixed.
I don't hear the remote participant for some reason, and the logs have no errors.
The interesting note is that if I build the sample app depending on the source code `implementation project(":livekit-android-sdk"),`, it works well.
But if I change the dependency on the published version `implementation("io.livekit:livekit-android:2.9.0")`, it fails to work.
I think that yesterday, acidently, the wrong/corrupted aar was published to production.
Could you check please?

**To Reproduce**
1. Build the base [sample-app-basic](https://github.com/livekit/client-sdk-android/tree/main/sample-app-basic) with dependency on `implementation("io.livekit:livekit-android:2.9.0")`
2. Run the app.
3. Observe that there is no audio from the remote participant.

**Expected behavior**
The audio from the remote participant should be present.

**Device Info:**
 - Device: [Samsung Xcover 6 pro]
 - OS: 14
 - LiveKit SDK version: 2.9.0

**Additional context**
The same version, 2.9.0, works well from the source code.

**Comment by davidliu** [comment]
Are you connecting to our cloud servers? There ended up being an issue on the server-side in conjunction with android v2.9.0. This should be cleared up now, try using v2.9.0 again.

**Comment by sokolyaka** [comment]
Yes, now it works well.
Thanks! And sorry for the alarm:)
