### ISSUE TITLE
SIGSEGV when leaving the the room

### ISSUE THREAD

**Issue by davidzhao** [livekit/client-sdk-android#52]
Reported by Matthew Brown in Slack:

I'm currently experiencing a SIGSEGV exception when leaving a video call on Android (both in our application which uses the LiveKit Android SDK, and the sample application you provide in the repo). We're using the latest 0.8.1 release, but this problem has existed in prior versions as well I believe.
This particular (or very similar) exception has been mentioned here before, but in the context of Flutter, and when connecting to a room (as opposed to disconnecting from one): https://livekit-users.slack.com/archives/C01KZ61HZRR/p1634861475005100?thread_ts=1634511225.150100&cid=C01KZ61HZRR
The crash is not reliably reproducible, and it happens maybe 1/5 times when disconnecting from a room, seemingly randomly. I've attached some error-level logging output (that was generated by the sample application) which includes the backtrace for the SIGSEGV (with a few preceding log statements in case they are relevant).

Server version: v0.15.3

[Logs: livekit_sigsegv.txt](https://github.com/livekit/client-sdk-android/files/7996868/livekit_sigsegv.txt)

**Comment by davidliu** [comment]
https://livekit-users.slack.com/archives/C01KVTJH6BX/p1643842426480329

**Comment by davidliu** [comment]
Reproed on M93, but seems to have disappeared with the M97 (entered and left around 50 times, didn't see it at all).

**Comment by davidliu** [comment]
Closing since SDK is upgraded to m97 now.
