### ISSUE TITLE
support Kotlin Multiplatform (KMP)

### ISSUE THREAD

**Issue by benkuly** [livekit/client-sdk-android#520]
Kotlin Multiplatform (KMP) allows to target nearly any platform (JVM/Android, JavaScript, WASM, Native/iOS/...). This library is already using Kotlin but targeting Android only. Would be awesome to see KMP support for it. I'm also open to help!

**Comment by davidzhao** [comment]
dupe of https://github.com/livekit/livekit/issues/3030

**Comment by davidzhao** [comment]
@benkuly thanks for your interest and offering your help! If you'd like to contribute to making this happen, we'd certainly welcome it. I've linked this to the other issue that had been open. Come to our [Slack community](https://livekit.io/join-slack) in #dev and let's discuss if there's a path forward here.

**Comment by zoujiaqing** [comment]
see here: https://github.com/zoujiaqing/livekit-kmp
