### ISSUE TITLE
How can I set the threshold for triggering the ActiveSpeakersChanged event? It's currently being triggered too easily.

### ISSUE THREAD

**Issue by tombang** [livekit/client-sdk-android#522]
I developed an app that listens for users speaking and calls a model to return results. However, in slightly noisy environments, the ActiveSpeakersChanged event is easily triggered, causing continuous input to the model and constant data returns, which is not reasonable.

Can I set the threshold for triggering the ActiveSpeakersChanged event?

**Comment by davidzhao** [comment]
this field is set on the server. currently it's not possible to modify from Android. raw settings are [here](https://github.com/livekit/livekit/blob/master/config-sample.yaml#L233)
