### ISSUE TITLE
Failed to transform '/Users/admin/.gradle/caches/modules-2/files-2.1/io.github.webrtc-sdk/android-prefixed/125.6422.05/df29fc7d002a11d35571bc723f0550b9abcf7697/android-prefixed-125.6422.05.aar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 61. (Run with --stacktrace for more details.)

### ISSUE THREAD

**Issue by nodzhang** [livekit/client-sdk-android#526]
when i build the project,build failed with this log
*envirment:
androidstudio version : 2024.1.2
android_gradle_plugin version:4.1.0
gradle version :gradle-6.7.1

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
 }

thanks

**Comment by davidliu** [comment]
Use a Java version 17 or up. The JDK already included in your Android Studio should be compatible with this.
