### ISSUE TITLE
 Unresolved reference: livekit

### ISSUE THREAD

**Issue by anishmenon** [livekit/client-sdk-android#53]
`e: /home/livekit-pract/client-sdk-android/livekit-android-sdk/src/main/java/io/livekit/android/room/PublisherTransportObserver.kt: (4, 8): Unresolved reference: livekit`

I'm getting this error

**Comment by davidzhao** [comment]
hey @anishmenon,

Did you follow the dev instructions [here](https://github.com/livekit/client-sdk-android#dev-environment)? I think this may be due to missing the submodules.

**Comment by anishmenon** [comment]
@davidzhao I've followed , I'm running sample-app 
actually, this is not getting imported,

import livekit.LivekitRtc

**Comment by anishmenon** [comment]
error screenshot : 
https://ibb.co/6DBhphM

**Comment by davidliu** [comment]
@anishmenon do you see the protocol subfolder filled out according to https://github.com/livekit/protocol ?

**Comment by anishmenon** [comment]
public final class RTCEngine implements io.livekit.android.room.SignalClient.Listener, org.webrtc.DataChannel.Observer {

different error now

screen : https://ibb.co/6DBhphM

**Comment by anishmenon** [comment]
i was able to build but it shows invalid URL I've specified my livekit wss URL
screen : https://ibb.co/NZjsHSj

**Comment by anishmenon** [comment]
itts only accepting wss://demo.livekit.cloud

**Comment by anishmenon** [comment]
its now working  I click where it says save values

**Comment by anishmenon** [comment]
@davidliu thanks
