### ISSUE TITLE
Whether topics in Data messages can be prioritized

### ISSUE THREAD

**Issue by nesror** [livekit/client-sdk-android#533]
**Is your feature request related to a problem? Please describe.**
Use Data messages to send data, some of which need to be guaranteed not to be lost, while others can be relatively lost if the network is not good.

**Describe the solution you'd like**
Whether different topics can be configured to handle the priority of different types of Data messages

**Describe alternatives you've considered**
At present, for important Data messages, the method of retry is not received. But this approach is cumbersome.

**Comment by davidliu** [comment]
Data messages are by default sent through the reliable data channel, which retransmits until received. Are you seeing data messages getting lost sent through the reliable channel?
