### ISSUE TITLE
There is an native crash while use the livekit

### ISSUE THREAD

**Issue by tombang** [livekit/client-sdk-android#534]
**Describe the bug**
There is an native crash while use the livekit

**To Reproduce**
The issue occurs intermittently.

**Expected behavior**
no crash occur

**Screenshots**
11-06 01:05:49.111 25697 25697 F DEBUG   : uid: 10119
11-06 01:05:49.111 25697 25697 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffff80000004
11-06 01:05:49.111 25697 25697 F DEBUG   :     x0  b4000074abc99470  x1  00000072d99d21b0  x2  00000072d99d21ef  x3  00000072d99d21ee
11-06 01:05:49.111 25697 25697 F DEBUG   :     x4  0000000000000000  x5  b40000740bc236c0  x6  907b2b2440830824  x7  27ab0df298ec8544
11-06 01:05:49.111 25697 25697 F DEBUG   :     x8  ffffffff80000000  x9  00000072eb9ea0ec  x10 0000000000030000  x11 0000000000000003
11-06 01:05:49.111 25697 25697 F DEBUG   :     x12 000000002bc4fdc0  x13 00000073f6e108a0  x14 00000072d99d1b80  x15 0000000000000000
11-06 01:05:49.111 25697 25697 F DEBUG   :     x16 0000000000000001  x17 00000076f7a631e4  x18 00000072d86f2000  x19 b4000074abc99470
11-06 01:05:49.111 25697 25697 F DEBUG   :     x20 b40000740bc122b0  x21 b40000749bc00010  x22 b40000744bbd4910  x23 aaaa00306e616c77
11-06 01:05:49.111 25697 25697 F DEBUG   :     x24 0000000000000005  x25 b40000746c8ad520  x26 000000006f4c0c48  x27 00000072d99d2358
11-06 01:05:49.111 25697 25697 F DEBUG   :     x28 00000072d99d2250  x29 00000072d99d21d0
11-06 01:05:49.111 25697 25697 F DEBUG   :     lr  00000072ebab87c0  sp  00000072d99d2170  pc  00000072ebab8808  pst 0000000060001000
11-06 01:05:49.111 25697 25697 F DEBUG   : backtrace:
11-06 01:05:49.112 25697 25697 F DEBUG   :       #00 pc 0000000000475808  /system_ext/priv-app/RobotServer/RobotServer.apk!libjingle_peerconnection_so.so (offset 0x5651000) (BuildId: 5f42006c533ab806)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #01 pc 000000000047570c  /system_ext/priv-app/RobotServer/RobotServer.apk!libjingle_peerconnection_so.so (offset 0x5651000) (Java_livekit_org_webrtc_NetworkMonitor_nativeNotifyOfNetworkConnect+32) (BuildId: 5f42006c533ab806)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #02 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #03 pc 000000000020a910  /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #04 pc 00000000001fdd82  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitor.notifyObserversOfNetworkConnect+50)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #05 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #06 pc 00000000001fdb24  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitor.-$$Nest$mnotifyObserversOfNetworkConnect+0)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #07 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #08 pc 00000000001fc498  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitor$2.onNetworkConnect+4)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #09 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #10 pc 00000000001fd0ac  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitorAutoDetect$SimpleNetworkCallback.onNetworkChanged+36)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #11 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #12 pc 00000000001fceec  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitorAutoDetect$SimpleNetworkCallback.onCapabilitiesChanged+76)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #13 pc 00000000020816d4  /memfd:jit-cache (deleted) (offset 0x2000000) (android.net.ConnectivityManager$CallbackHandler.handleMessage+1604)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #14 pc 000000000055fa60  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+192) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #15 pc 0000000000562d68  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1032) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #16 pc 00000000005628c0  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+560) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #17 pc 0000000000561ad4  /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+580) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #18 pc 000000000021096c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #19 pc 000000000027b478  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #20 pc 00000000006118e8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+464) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #21 pc 0000000000659b9c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1292) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #22 pc 00000000000ba650  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: bf5f1ce73f89cca7d6a062eb7877e86a)
11-06 01:05:49.112 25697 25697 F DEBUG   :       #23 pc 0000000000053ffc  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: bf5f1ce73f89cca7d6a062eb7877e86a)

**Device Info:**
 - Device: Google pixel
 - OS: Android 13
 - LiveKit SDK version: 2.7.0

**Additional context**

**Comment by bitristan** [comment]
Open WebRTC log
`
        LiveKit.enableWebRTCLogging = true
`

And maybe there are logs in logcat like below
`
11-11 20:47:55.328  2187  3356 E rtc     : #
11-11 20:47:55.328  2187  3356 E rtc     : # Fatal error in: ../../../pc/audio_rtp_receiver.cc, line 98
11-11 20:47:55.328  2187  3356 E rtc     : # last system error: 0
11-11 20:47:55.328  2187  3356 E rtc     : # Check failed: (&signaling_thread_checker_)->IsCurrent()
11-11 20:47:55.328  2187  3356 E rtc     : # # Expected: TQ: 0x71aec84c80 Thread: 0x71ae8f8d50
11-11 20:47:55.328  2187  3356 E rtc     : # Actual:   TQ: 0x71aec848c0 Thread: 0x71aebfbd50
11-11 20:47:55.328  2187  3356 E rtc     : TaskQueue doesn't match
11-11 20:47:55.328  2187  3356 E rtc     : 
`

Then you know what's wong.

**Comment by davidliu** [comment]
This was fixed in the webrtc-sdk but the wrong version was depended upon in 2.7.0. This should be fixed if you update to the latest SDK.

**Comment by tombang** [comment]
The same error : 2.10.0:

11-11 10:55:01.150 19462 19462 F DEBUG   : pid: 3513, tid: 9842, name: ConnectivityThr  >>> com.tcl.robot.server:remote <<<
11-11 10:55:01.150 19462 19462 F DEBUG   : uid: 10120
11-11 10:55:01.150 19462 19462 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x00000071dda217b0
11-11 10:55:01.150 19462 19462 F DEBUG   :     x0  b40000711da90830  x1  0000006f2afee120  x2  0000006f2afee15f  x3  0000006f2afee15e
11-11 10:55:01.150 19462 19462 F DEBUG   :     x4  0000000000000000  x5  b40000707dac4954  x6  000000002403a8c0  x7  000000002403a8c0
11-11 10:55:01.150 19462 19462 F DEBUG   :     x8  b4000071dda217b0  x9  0000000000000000  x10 0000000000030000  x11 0000000000000003
11-11 10:55:01.151 19462 19462 F DEBUG   :     x12 000000009dac2740  x13 00000070688108a0  x14 0000006f2afedaf0  x15 0000000000000000
11-11 10:55:01.151 19462 19462 F DEBUG   :     x16 0000000000000001  x17 000000737c0521e4  x18 0000006f2a3b8000  x19 b40000711da90830
11-11 10:55:01.151 19462 19462 F DEBUG   :     x20 b40000707dacef70  x21 b40000710da738b0  x22 b4000070bdad3570  x23 aaaa00306e616c77
11-11 10:55:01.151 19462 19462 F DEBUG   :     x24 0000000000000005  x25 b4000070adbceb70  x26 0000000070b79c48  x27 0000006f2afee2c8
11-11 10:55:01.151 19462 19462 F DEBUG   :     x28 0000006f2afee1c0  x29 0000006f2afee140
11-11 10:55:01.151 19462 19462 F DEBUG   :     lr  0000006f630aa814  sp  0000006f2afee0e0  pc  00000071dda217b0  pst 0000000060001000
11-11 10:55:01.151 19462 19462 F DEBUG   : backtrace:
11-11 10:55:01.151 19462 19462 F DEBUG   :       #00 pc 00000000000037b0  [anon:scudo:primary]
11-11 10:55:01.151 19462 19462 F DEBUG   :       #01 pc 0000000000475810  /system_ext/priv-app/RobotServer/RobotServer.apk!libjingle_peerconnection_so.so (offset 0x565a000) (BuildId: 5f42006c533ab806)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #02 pc 000000000047570c  /system_ext/priv-app/RobotServer/RobotServer.apk!libjingle_peerconnection_so.so (offset 0x565a000) (Java_livekit_org_webrtc_NetworkMonitor_nativeNotifyOfNetworkConnect+32) (BuildId: 5f42006c533ab806)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #03 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #04 pc 000000000020a910  /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #05 pc 00000000001fcf1a  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitor.notifyObserversOfNetworkConnect+50)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #06 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #07 pc 00000000001fccbc  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitor.-$$Nest$mnotifyObserversOfNetworkConnect+0)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #08 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #09 pc 00000000001fb630  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitor$2.onNetworkConnect+4)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #10 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #11 pc 00000000001fc244  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitorAutoDetect$SimpleNetworkCallback.onNetworkChanged+36)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #12 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #13 pc 00000000001fc084  /system_ext/priv-app/RobotServer/RobotServer.apk (livekit.org.webrtc.NetworkMonitorAutoDetect$SimpleNetworkCallback.onCapabilitiesChanged+76)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #14 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #15 pc 0000000000019102  /apex/com.android.tethering/javalib/framework-connectivity.jar (android.net.ConnectivityManager$CallbackHandler.handleMessage+298)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #16 pc 000000000055fa60  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+192) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #17 pc 0000000000562d68  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1032) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #18 pc 00000000005628c0  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+560) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #19 pc 0000000000561ad4  /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+580) (BuildId: 43410311cd7bb269e6d893d19a3a36b0ad57ef1c)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #20 pc 000000000021096c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #21 pc 000000000027b478  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #22 pc 00000000006118e8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+464) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #23 pc 0000000000659b9c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1292) (BuildId: 3fdfb8b8ec5407af450c28a00ba584a8)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #24 pc 00000000000ba650  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: bf5f1ce73f89cca7d6a062eb7877e86a)
11-11 10:55:01.151 19462 19462 F DEBUG   :       #25 pc 0000000000053ffc  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: bf5f1ce73f89cca7d6a062eb7877e86a)
11-11 10:55:01.201  1524 19467 I am_crash: [1524,0,com.tcl.robot.server:remote,681098821,Native crash,Segmentation fault,unknown,0]
