### ISSUE TITLE
USB camera not listing 

### ISSUE THREAD

**Issue by anishmenon** [livekit/client-sdk-android#54]
How we can read the External camera now it only reads the front and back camera
see an app that reads all external cameras

https://play.google.com/store/apps/details?id=com.shenyaocn.android.usbcamera

**Comment by anishmenon** [comment]
can u revert an example

    var videoTrackCaptureDefaults: LocalVideoTrackOptions = LocalVideoTrackOptions()

**Comment by anishmenon** [comment]
var videoTrackCaptureDefaults: LocalVideoTrackOptions = LocalVideoTrackOptions(deviceId = "/dev/video63")

**Comment by davidliu** [comment]
Again, get the device name through the process I mentioned in the previous comment.

**Comment by anishmenon** [comment]
Camera1Enumerator 
Camera2Enumerator

are basically throw front camera and back cameras it won't list USB / external

**Comment by anishmenon** [comment]
https://github.com/libuvc/libuvc
this library will be able to throw all connected USB  video devices

**Comment by davidliu** [comment]
Hmm I think this may be out of scope currently, if the phone doesn't support discovering the USB camera through Camera2.

You can use libuvc/other 3rd party libraries to create your own `org.webrtc.VideoCapturer` and VideoTrack to support this feature.

**Comment by davidliu** [comment]
Closing as not planned.
