### ISSUE TITLE
Does the Android sdk have a way to adjust the volume of microphone acquisition

### ISSUE THREAD

**Issue by nesror** [livekit/client-sdk-android#542]
**Is your feature request related to a problem? Please describe.**
val localParticipant = room.localParticipant
localParticipant.setMicrophoneEnabled(true)
Then you need to modify your own capture volume
Or does svr's kotlin sdk have a way to control the volume of a certain track

**Describe the solution you'd like**
Can modify Microphone capture volume
Or does svr's kotlin sdk have a way to control the volume of a certain track

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by davidliu** [comment]
We don't have an in-built function for doing this, but you can set an AudioProcessor through `room.audioProcessingController.capturePostProcessor` or passing in AudioOptions when you create the room.

Writing a processor to change the value is fairly simple, here's an example:

```
class GainProcessor : AudioProcessorInterface {

    var gainMultiplier = 1f

    override fun isEnabled(): Boolean = true

    override fun getName(): String = "gain_processor"

    override fun initializeAudioProcessing(sampleRateHz: Int, numChannels: Int) {
        // nothing to do
    }

    override fun resetAudioProcessing(newRate: Int) {
        // Nothing to do
    }

    override fun processAudio(numBands: Int, numFrames: Int, buffer: ByteBuffer) {
        // Position to the front and make sure you use the native byte order.
        buffer.position(0)
        buffer.order(ByteOrder.nativeOrder())

        // Audio processing is done with Float PCM
        val floatBuffer = buffer.asFloatBuffer()

        // Linearly scale the audio data by a multiplier
        for (i in 0 until floatBuffer.capacity()) {
            val sample = floatBuffer[i]
            floatBuffer.put(i, sample * gainMultiplier)
        }
    }
}

```
