### ISSUE TITLE
How to publish a VideoTrack with BitmapFrameCapture ?

### ISSUE THREAD

**Issue by kavmors** [livekit/client-sdk-android#554]
I'm trying to send an user-specified bitmap image from my Android APP. For this I publish a VideoTrack with Android SDK:

```
val bmpCapture = BitmapFrameCapturer()

// called on APP starting
fun startPublish() {
    val track = localParticipant.createVideoTrack(name = "user-image", capturer = bmpCapture)
    track.startCapture()
    localParticipant.publishVideoTrack(track)
}

// called after user selected an image
fun updateImage(image: Bitmap) {
    bmpCapture.pushBitmap(image)
}
```

And then I try to receive it with Python Agent:

```
def on_track_subscribed(track, publication, participant):
    stream = rtc.VideoStream(track)
    async for event in stream:
        log("image received")
    await stream.aclose()

room.on("track_subscribed", on_track_subscribed)
```

However, When the APP starts and calls publishVideoTrack, the Agent does not trigger the track_subscribed callback.
Until I select an image and call updateImage, the track_subscribed callback is triggered.

I also check my local Livekit-Server log, it says "track published with high delay" after updateImage called

What is it means? How can I subscribe the Track once I call publishVideoTrack?

**Comment by davidliu** [comment]
I think using a video track would not be appropriate for this, since they're for actual video with ongoing frames.

You can send the image over the datachannel directly (LocalParticipant.publishData), which would be a lot less hassle.

**Comment by kavmors** [comment]
OK I'll try it. Thanks
