### ISSUE TITLE
No message received for SignalResponse.MessageCase.UPDATE

### ISSUE THREAD

**Issue by hadesss123** [livekit/client-sdk-android#57]
When user A joins the room first and user B joins the room later, user A does not receive the message that B joins the room (SignalResponse.MessageCase.UPDATE), nor does user A receive the offer message about user B

**Comment by hadesss123** [comment]
Client Version: 0.9.0-SNAPSHOT
Server Version: v0.15.4  
@davidliu

**Comment by davidliu** [comment]
@hadesss123 Can User B see User A's streams?

@davidzhao This seems like a server issue? Any idea how this could be? Haven't ever really seen this happen.

**Comment by hadesss123** [comment]
I can be sure that A and B join the same room. Because A joins the room first, and B joins the room later. "OtherParticipants" in B's "JoinResponse" contains A, but A has not received the SignalResponse.MessageCase.UPDATE added by B @davidzhao @davidliu

**Comment by davidliu** [comment]
Does it also happen if participant A is on different platform? Can you try with https://example.livekit.io ?
