### ISSUE TITLE
Media connections too slow.

### ISSUE THREAD

**Issue by CensorKao** [livekit/client-sdk-android#60]
Media connections are established 5 seconds more with livekit server. This means that with livekit server the average time between a customer calling the subscription operation and the video being actually played on their device, it could average around 5 seconds. With mediasoup it averages 0.25 seconds.

Android Client Version: 0.9.0-SNAPSHOT
Server Version: v0.15.4

**Comment by davidliu** [comment]
Should be fixed in main now.
