### ISSUE TITLE
Crash when connect peer to peer

### ISSUE THREAD

**Issue by haohmaruru** [livekit/client-sdk-android#78]
I use version 0.9.1 and i have crash log when connect:

Fatal Exception: java.lang.NullPointerException
subscriber.peerConnection.localDescription must not be null.

io.livekit.android.room.RTCEngine.sendSyncState (RTCEngine.kt:705)
io.livekit.android.room.Room.sendSyncState (Room.kt:408)
io.livekit.android.room.Room.onSignalConnected (Room.kt:629)
io.livekit.android.room.RTCEngine$reconnect$job$1.invokeSuspend (RTCEngine.kt:364)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
kotlinx.coroutines.internal.LimitedDispatcher.run (LimitedDispatcher.kt:42)
kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:95)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:570)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:749)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:677)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:664)

Please check my issue.
Thanks team

**Comment by davidliu** [comment]
Is this happening upon the initial connect, or does it occur a little bit
after connection?

**Comment by haohmaruru** [comment]
it happeng when initial connect

**Comment by davidliu** [comment]
Got it, I'll check it out.

**Comment by davidliu** [comment]
Does this happen consistently or just sometimes?

**Comment by haohmaruru** [comment]
Sometime it happen and sometime work fine

**Comment by haohmaruru** [comment]
hi @davidliu i have another crash with log in version0.9.1 when after use function "LiveKit.connect":

Fatal Exception: java.lang.NullPointerException
subscriber.peerConnection.localDescription must not be null

io.livekit.android.room.RTCEngine.sendSyncState (RTCEngine.kt:705)
io.livekit.android.room.Room.sendSyncState (Room.kt:408)
io.livekit.android.room.Room.onSignalConnected (Room.kt:629)
io.livekit.android.room.RTCEngine$reconnect$job$1.invokeSuspend (RTCEngine.kt:364)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
kotlinx.coroutines.internal.LimitedDispatcher.run (LimitedDispatcher.kt:42)
kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:95)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:570)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:749)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:677)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:664)
