### ISSUE TITLE
Add override customizations for AudioDeviceModule

### ISSUE THREAD

**Issue by davidliu** [livekit/client-sdk-android#80]
>On some Sony device (if needed, I can check which one exactly) we had horrible echoes when HW AEC was enabled. On the other Hand, on a Pixel 2 the situation was the opposite, with HW disabled we had more echoes than without.

https://livekit-users.slack.com/archives/C01KVTJH6BX/p1651666159905679?thread_ts=1651652293.686499&cid=C01KVTJH6BX

**Comment by symphonybiz** [comment]
That particular device was a Sony Xperia Z5 (E6653)
