### ISSUE TITLE
Unable to run sample app

### ISSUE THREAD

**Issue by sahaypratik** [livekit/client-sdk-android#96]
While running the build I am getting this error "**Unresolved reference: livekit**" in **livekit-android-sdk** module. Its not able to import classes in **livekit**. What's the fix or workaround so that I can setup and run sample app

**Comment by davidliu** [comment]
Have you followed the instructions for setting up the dev environment?

https://github.com/livekit/client-sdk-android#dev-environment

**Comment by sahaypratik** [comment]
@davidliu I am facing one more error when I am trying to implement in new project. Error is **Could not find com.github.webrtc-sdk:android:97.4692.04.** Do I have to add webrtc library explicitly to my project? Here is screenshot of the error [https://i.postimg.cc/L6MkZXjF/Screenshot-2022-06-22-165652.png](url)

**Comment by YanxuLi** [comment]
me too.
Unresolved reference: livekit

import io.livekit.android.util.LKLog
**_import livekit.LivekitRtc_** this line
import org.webrtc.*

**Comment by YanxuLi** [comment]
I used the remote library and it worked . By the way, can I use LiveKit in my Java project ?

**Comment by sahaypratik** [comment]
@YanxuLi which remote library did you use and how to did implement in the sample app?

**Comment by sahaypratik** [comment]
@davidliu   protocol submodule is not an android/ java library so there is no way to import it in android project so how should I add it to the project and initialize it, can you please guide me through the process.

**Comment by davidliu** [comment]
Again, https://github.com/livekit/client-sdk-android#dev-environment
